// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2022.2_1/1019737 Production Release
//       HLS date: Mon Nov 21 20:05:27 PST 2022
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: HLS_student@wifi-salsa-197.priv.enst-bretagne.fr
// Generated date: Tue Mar 14 16:02:11 CET 2023
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model FFT
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Process: SC_METHOD update_proc
// Static sensitivity: sensitive  << clk << rst << data_valid_source << data_req_sink << in_real << in_img << ccs_rtl_SIG_out_real << ccs_rtl_SIG_out_img << ccs_rtl_SIG_data_valid_sink << ccs_rtl_SIG_data_req_source;

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   // none.sc_in field_key=clk:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-582:clk:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-582
   sc_logic t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_582_0; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-583:rst:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-583
   sc_logic t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_583_1; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_583_1); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_583_1); // then write to RTL port
   
   // none.sc_in field_key=data_valid_source:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-584:data_valid_source:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-584
   sc_logic t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_584_2; // NPS - LV to hold field
   type_to_vector(data_valid_source.read(),1,t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_584_2); // read orig port and type convert
   ccs_rtl_SIG_data_valid_source.write(t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_584_2); // then write to RTL port
   
   // none.sc_in field_key=data_req_sink:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-585:data_req_sink:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-585
   sc_logic t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_585_3; // NPS - LV to hold field
   type_to_vector(data_req_sink.read(),1,t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_585_3); // read orig port and type convert
   ccs_rtl_SIG_data_req_sink.write(t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_585_3); // then write to RTL port
   
   // none.sc_in field_key=in_real:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-586:in_real:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-586
   sc_lv< 23 > t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_586_4; // NPS - LV to hold field
   type_to_vector(in_real.read(),23,t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_586_4); // read orig port and type convert
   ccs_rtl_SIG_in_real.write(t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_586_4); // then write to RTL port
   
   // none.sc_in field_key=in_img:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-587:in_img:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-587
   sc_lv< 23 > t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_587_5; // NPS - LV to hold field
   type_to_vector(in_img.read(),23,t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_587_5); // read orig port and type convert
   ccs_rtl_SIG_in_img.write(t_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_587_5); // then write to RTL port
   
   // none.sc_out field_key=out_real:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-588:out_real:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-588
   ac_fixed<23, 18, true, AC_RND_INF, AC_SAT > d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_588_6;
   vector_to_type(ccs_rtl_SIG_out_real.read(), 23, &d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_588_6);
   out_real.write(d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_588_6);
   
   // none.sc_out field_key=out_img:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-589:out_img:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-589
   ac_fixed<23, 18, true, AC_RND_INF, AC_SAT > d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_589_7;
   vector_to_type(ccs_rtl_SIG_out_img.read(), 23, &d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_589_7);
   out_img.write(d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_589_7);
   
   // none.sc_out field_key=data_valid_sink:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-590:data_valid_sink:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-590
   bool d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_590_8;
   vector_to_type(ccs_rtl_SIG_data_valid_sink.read(), 1, &d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_590_8);
   data_valid_sink.write(d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_590_8);
   
   // none.sc_out field_key=data_req_source:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-591:data_req_source:9e67edc8-5f2d-4cdf-a528-29cfa8c58f38-591
   bool d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_591_9;
   vector_to_type(ccs_rtl_SIG_data_req_source.read(), 1, &d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_591_9);
   data_req_source.write(d_9e67edc8_5f2d_4cdf_a528_29cfa8c58f38_591_9);
   
}
