
//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2022.2_1/1019737 Production Release
//  HLS Date:       Mon Nov 21 20:05:27 PST 2022
// 
//  Generated by:   HLS_student@wifi-salsa-197.priv.enst-bretagne.fr
//  Generated date: Tue Mar 14 16:34:13 2023
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    FFT_COMPORTEMENT
// ------------------------------------------------------------------


module FFT_COMPORTEMENT (
  clk, rst, data_valid_source, data_req_sink, in_real, in_img, out_real, out_img,
      data_valid_sink, data_req_source
);
  input clk;
  input rst;
  input data_valid_source;
  input data_req_sink;
  input [22:0] in_real;
  input [22:0] in_img;
  output [22:0] out_real;
  output [22:0] out_img;
  output data_valid_sink;
  reg data_valid_sink;
  output data_req_source;
  reg data_req_source;


  // Interconnect Declarations
  reg while_if_if_2_conc_itm_1_22;
  reg [20:0] while_if_if_2_conc_itm_1_21_1;
  reg while_if_if_2_conc_itm_1_0;
  reg while_if_if_2_mux_3_itm_1;
  reg [20:0] while_if_if_2_mux_4_itm_1;
  reg while_if_if_2_mux_5_itm_1;
  wire [31:0] while_if_if_2_acc_tmp;
  wire [32:0] nl_while_if_if_2_acc_tmp;
  wire [31:0] while_if_if_1_acc_tmp;
  wire [32:0] nl_while_if_if_1_acc_tmp;
  wire and_dcpl_5;
  wire or_dcpl_7;
  wire and_dcpl_14;
  wire or_dcpl_10;
  wire or_dcpl_12;
  wire or_dcpl_13;
  wire or_dcpl_16;
  wire or_dcpl_17;
  wire or_dcpl_18;
  wire or_dcpl_20;
  wire or_dcpl_22;
  wire or_dcpl_23;
  wire or_dcpl_25;
  wire or_dcpl_26;
  wire or_dcpl_28;
  wire or_dcpl_30;
  wire or_dcpl_32;
  wire or_dcpl_34;
  wire or_dcpl_35;
  wire or_dcpl_37;
  wire or_dcpl_39;
  wire or_dcpl_41;
  wire or_dcpl_43;
  wire or_dcpl_44;
  wire or_dcpl_46;
  wire or_dcpl_48;
  wire or_dcpl_50;
  wire or_dcpl_52;
  wire while_if_land_2_lpi_1_dfm_1;
  reg processing_sva;
  reg j_sva_3;
  reg while_if_if_nor_cse_sva_1;
  wire [27:0] i_sva_31_4_mx0;
  wire [2:0] i_sva_2_0_mx0;
  wire [27:0] j_sva_31_4_mx0;
  wire [2:0] j_sva_2_0_mx0;
  wire [29:0] but_11_acc_9_psp_sva_1;
  wire [30:0] nl_but_11_acc_9_psp_sva_1;
  wire [29:0] but_11_acc_6_psp_sva_1;
  wire [30:0] nl_but_11_acc_6_psp_sva_1;
  wire [29:0] but_11_acc_3_psp_sva_1;
  wire [31:0] nl_but_11_acc_3_psp_sva_1;
  wire [29:0] but_11_acc_psp_sva_1;
  wire [30:0] nl_but_11_acc_psp_sva_1;
  wire [29:0] but_9_acc_9_psp_sva_1;
  wire [30:0] nl_but_9_acc_9_psp_sva_1;
  wire [29:0] but_9_acc_6_psp_sva_1;
  wire [30:0] nl_but_9_acc_6_psp_sva_1;
  wire [29:0] but_9_acc_3_psp_sva_1;
  wire [31:0] nl_but_9_acc_3_psp_sva_1;
  wire [29:0] but_9_acc_psp_sva_1;
  wire [30:0] nl_but_9_acc_psp_sva_1;
  wire while_if_if_nor_cse_sva_1_1;
  wire [23:0] but_10_mul_2_psp_sva_1;
  wire [24:0] nl_but_10_mul_2_psp_sva_1;
  wire [23:0] but_10_mul_1_psp_sva_1;
  wire [24:0] nl_but_10_mul_1_psp_sva_1;
  reg but_6_slc_but_6_acc_12_psp_23_2_itm_1;
  reg [20:0] but_6_conc_9_ncse_21_1_sva_1;
  reg but_6_conc_9_ncse_0_sva_1;
  reg but_6_slc_but_6_acc_psp_23_2_itm_1;
  reg [20:0] but_6_conc_8_ncse_21_1_sva_1;
  reg but_6_conc_8_ncse_0_sva_1;
  reg [23:0] but_7_mul_2_psp_sva_1;
  wire [24:0] nl_but_7_mul_2_psp_sva_1;
  reg [23:0] but_7_mul_1_psp_sva_1;
  wire [24:0] nl_but_7_mul_1_psp_sva_1;
  reg [23:0] but_5_mul_2_psp_sva_1;
  wire [24:0] nl_but_5_mul_2_psp_sva_1;
  reg [23:0] but_5_mul_1_psp_sva_1;
  wire [24:0] nl_but_5_mul_1_psp_sva_1;
  wire [20:0] but_2_conc_78_21_1;
  wire but_2_conc_78_0;
  wire [20:0] but_3_conc_9_ncse_21_1_sva_1;
  wire but_3_conc_9_ncse_0_sva_1;
  wire [20:0] but_2_conc_80_21_1;
  wire but_2_conc_80_0;
  wire [20:0] but_3_conc_8_ncse_21_1_sva_1;
  wire but_3_conc_8_ncse_0_sva_1;
  wire [20:0] fft_stage1_imag_conc_3_21_1;
  wire fft_stage1_imag_conc_3_0;
  wire [20:0] but_1_conc_9_ncse_21_1_sva_1;
  wire but_1_conc_9_ncse_0_sva_1;
  wire [20:0] fft_stage1_real_conc_3_21_1;
  wire fft_stage1_real_conc_3_0;
  wire [20:0] but_1_conc_8_ncse_21_1_sva_1;
  wire but_1_conc_8_ncse_0_sva_1;
  wire [22:0] cx_in_imag_3_sva_mx0;
  wire [22:0] cx_in_imag_7_sva_mx0;
  wire [22:0] cx_in_real_3_sva_mx0;
  wire [22:0] cx_in_real_7_sva_mx0;
  wire [22:0] cx_in_imag_1_sva_mx0;
  wire [22:0] cx_in_imag_5_sva_mx0;
  wire [22:0] cx_in_real_1_sva_mx0;
  wire [22:0] cx_in_real_5_sva_mx0;
  wire [22:0] cx_in_imag_2_sva_mx0;
  wire [22:0] cx_in_imag_6_sva_mx0;
  wire [22:0] cx_in_real_2_sva_mx0;
  wire [22:0] cx_in_real_6_sva_mx0;
  wire [22:0] cx_in_imag_0_sva_mx0;
  wire [22:0] cx_in_imag_4_sva_mx0;
  wire [22:0] cx_in_real_0_sva_mx0;
  wire [22:0] cx_in_real_4_sva_mx0;
  reg i_sva_3;
  reg while_if_aelse_nor_itm_1;
  reg while_stage_0_2;
  reg while_asn_itm_2;
  reg while_if_land_1_lpi_1_dfm_st_1;
  reg while_if_while_if_if_and_itm_2;
  reg while_stage_0_3;
  reg while_if_land_2_lpi_1_dfm_st_1;
  reg [2:0] i_sva_2_0;
  wire [24:0] but_11_acc_11_psp_1_sva_1;
  wire [25:0] nl_but_11_acc_11_psp_1_sva_1;
  wire [24:0] but_11_acc_8_psp_1_sva_1;
  wire [25:0] nl_but_11_acc_8_psp_1_sva_1;
  wire [24:0] but_11_acc_5_psp_1_sva_1;
  wire [25:0] nl_but_11_acc_5_psp_1_sva_1;
  wire [24:0] but_11_acc_2_psp_1_sva_1;
  wire [25:0] nl_but_11_acc_2_psp_1_sva_1;
  wire [24:0] but_9_acc_11_psp_1_sva_1;
  wire [25:0] nl_but_9_acc_11_psp_1_sva_1;
  wire [24:0] but_9_acc_8_psp_1_sva_1;
  wire [25:0] nl_but_9_acc_8_psp_1_sva_1;
  wire [24:0] but_9_acc_5_psp_1_sva_1;
  wire [25:0] nl_but_9_acc_5_psp_1_sva_1;
  wire [24:0] but_9_acc_2_psp_1_sva_1;
  wire [25:0] nl_but_9_acc_2_psp_1_sva_1;
  wire while_if_while_if_and_1_mx0w0;
  wire [23:0] but_10_acc_14_psp_sva_1;
  wire [24:0] nl_but_10_acc_14_psp_sva_1;
  wire [23:0] but_10_acc_13_psp_sva_1;
  wire [24:0] nl_but_10_acc_13_psp_sva_1;
  wire [23:0] but_10_acc_12_psp_sva_1;
  wire [24:0] nl_but_10_acc_12_psp_sva_1;
  wire [23:0] but_10_acc_psp_sva_1;
  wire [24:0] nl_but_10_acc_psp_sva_1;
  wire [23:0] but_7_acc_14_psp_sva_1;
  wire [24:0] nl_but_7_acc_14_psp_sva_1;
  wire [23:0] but_7_acc_13_psp_sva_1;
  wire [24:0] nl_but_7_acc_13_psp_sva_1;
  wire [23:0] but_7_acc_12_psp_sva_1;
  wire [24:0] nl_but_7_acc_12_psp_sva_1;
  wire [23:0] but_7_acc_psp_sva_1;
  wire [24:0] nl_but_7_acc_psp_sva_1;
  wire [23:0] but_5_acc_14_psp_sva_1;
  wire [24:0] nl_but_5_acc_14_psp_sva_1;
  wire [23:0] but_5_acc_13_psp_sva_1;
  wire [24:0] nl_but_5_acc_13_psp_sva_1;
  wire [23:0] but_5_acc_12_psp_sva_1;
  wire [24:0] nl_but_5_acc_12_psp_sva_1;
  wire [23:0] but_5_acc_psp_sva_1;
  wire [24:0] nl_but_5_acc_psp_sva_1;
  wire [23:0] but_6_acc_14_psp_sva_1;
  wire [24:0] nl_but_6_acc_14_psp_sva_1;
  wire [23:0] but_3_acc_12_psp_sva_1;
  wire [24:0] nl_but_3_acc_12_psp_sva_1;
  wire [23:0] but_6_acc_13_psp_sva_1;
  wire [24:0] nl_but_6_acc_13_psp_sva_1;
  wire [23:0] but_3_acc_psp_sva_1;
  wire [24:0] nl_but_3_acc_psp_sva_1;
  wire [23:0] but_6_acc_12_psp_sva_1;
  wire [24:0] nl_but_6_acc_12_psp_sva_1;
  wire [23:0] but_6_acc_psp_sva_1;
  wire [24:0] nl_but_6_acc_psp_sva_1;
  wire [23:0] but_4_acc_14_psp_sva_1;
  wire [24:0] nl_but_4_acc_14_psp_sva_1;
  wire [23:0] but_1_acc_12_psp_sva_1;
  wire [24:0] nl_but_1_acc_12_psp_sva_1;
  wire [23:0] but_4_acc_13_psp_sva_1;
  wire [24:0] nl_but_4_acc_13_psp_sva_1;
  wire [23:0] but_1_acc_psp_sva_1;
  wire [24:0] nl_but_1_acc_psp_sva_1;
  wire [23:0] but_4_acc_12_psp_sva_1;
  wire [24:0] nl_but_4_acc_12_psp_sva_1;
  wire [23:0] but_4_acc_psp_sva_1;
  wire [24:0] nl_but_4_acc_psp_sva_1;
  wire [23:0] but_2_acc_14_psp_sva_1;
  wire [24:0] nl_but_2_acc_14_psp_sva_1;
  wire [23:0] but_2_acc_13_psp_sva_1;
  wire [24:0] nl_but_2_acc_13_psp_sva_1;
  wire [23:0] but_2_acc_12_psp_sva_1;
  wire [24:0] nl_but_2_acc_12_psp_sva_1;
  wire [23:0] but_2_acc_psp_sva_1;
  wire [24:0] nl_but_2_acc_psp_sva_1;
  wire [23:0] but_acc_14_psp_sva_1;
  wire [24:0] nl_but_acc_14_psp_sva_1;
  wire [23:0] but_acc_13_psp_sva_1;
  wire [24:0] nl_but_acc_13_psp_sva_1;
  wire [23:0] but_acc_12_psp_sva_1;
  wire [24:0] nl_but_acc_12_psp_sva_1;
  wire [23:0] but_acc_psp_sva_1;
  wire [24:0] nl_but_acc_psp_sva_1;
  wire nand_10_ssc;
  wire [27:0] j_sva_dfm_mx0_31_4;
  wire j_sva_dfm_mx0_3;
  wire [2:0] j_sva_dfm_mx0_2_0;
  wire or_12_ssc;
  wire [27:0] i_sva_dfm_mx0_31_4;
  wire i_sva_dfm_mx0_3;
  wire [2:0] i_sva_dfm_mx0_2_0;
  wire while_if_aif_1_while_if_aelse_1_nand_cse;
  reg but_4_slc_but_4_acc_14_psp_23_2_itm_1;
  reg [20:0] but_4_conc_11_ncse_21_1_sva_1;
  reg but_4_conc_11_ncse_0_sva_1;
  reg but_4_slc_but_4_acc_13_psp_23_2_itm_1;
  reg [20:0] but_4_conc_10_ncse_21_1_sva_1;
  reg but_4_conc_10_ncse_0_sva_1;
  reg but_4_slc_but_4_acc_12_psp_23_2_itm_1;
  reg [20:0] fft_stage2_imag_0_21_1_sva_1;
  reg fft_stage2_imag_0_0_sva_1;
  reg but_4_slc_but_4_acc_psp_23_2_itm_1;
  reg [20:0] fft_stage2_real_0_21_1_sva_1;
  reg fft_stage2_real_0_0_sva_1;
  reg but_2_slc_but_2_acc_14_psp_23_2_itm_1;
  reg [20:0] but_2_conc_11_ncse_21_1_sva_1;
  reg but_2_conc_11_ncse_0_sva_1;
  reg but_2_slc_but_2_acc_13_psp_23_2_itm_1;
  reg [20:0] but_2_conc_10_ncse_21_1_sva_1;
  reg but_2_conc_10_ncse_0_sva_1;
  reg but_slc_but_acc_14_psp_23_2_itm_1;
  reg [20:0] but_conc_11_ncse_21_1_sva_1;
  reg but_conc_11_ncse_0_sva_1;
  reg but_slc_but_acc_13_psp_23_2_itm_1;
  reg [20:0] but_conc_10_ncse_21_1_sva_1;
  reg but_conc_10_ncse_0_sva_1;
  reg [27:0] j_sva_31_4;
  reg [2:0] j_sva_2_0;
  reg [27:0] i_sva_31_4;
  wire i_or_cse;
  wire j_or_cse;
  wire xor_dcpl;
  wire [23:0] z_out;
  wire [23:0] z_out_1;
  wire [23:0] z_out_2;
  wire [23:0] z_out_3;
  reg [22:0] cx_in_real_3_sva;
  reg [22:0] cx_in_real_4_sva;
  reg [22:0] cx_in_real_2_sva;
  reg [22:0] cx_in_real_5_sva;
  reg [22:0] cx_in_real_1_sva;
  reg [22:0] cx_in_real_6_sva;
  reg [22:0] cx_in_real_0_sva;
  reg [22:0] cx_in_real_7_sva;
  reg [22:0] cx_in_imag_3_sva;
  reg [22:0] cx_in_imag_4_sva;
  reg [22:0] cx_in_imag_2_sva;
  reg [22:0] cx_in_imag_5_sva;
  reg [22:0] cx_in_imag_1_sva;
  reg [22:0] cx_in_imag_6_sva;
  reg [22:0] cx_in_imag_0_sva;
  reg [22:0] cx_in_imag_7_sva;
  reg [20:0] cx_out_real_0_21_1_sva_dfm;
  reg cx_out_real_0_0_sva_dfm;
  reg [20:0] cx_out_real_1_21_1_sva_dfm;
  reg cx_out_real_1_0_sva_dfm;
  reg [20:0] cx_out_real_2_21_1_sva_dfm;
  reg cx_out_real_2_0_sva_dfm;
  reg [20:0] cx_out_real_3_21_1_sva_dfm;
  reg cx_out_real_3_0_sva_dfm;
  reg [20:0] cx_out_real_4_21_1_sva_dfm;
  reg cx_out_real_4_0_sva_dfm;
  reg [20:0] cx_out_real_5_21_1_sva_dfm;
  reg cx_out_real_5_0_sva_dfm;
  reg [20:0] cx_out_real_6_21_1_sva_dfm;
  reg cx_out_real_6_0_sva_dfm;
  reg [20:0] cx_out_real_7_21_1_sva_dfm;
  reg cx_out_real_7_0_sva_dfm;
  reg [20:0] cx_out_imag_0_21_1_sva_dfm;
  reg cx_out_imag_0_0_sva_dfm;
  reg [20:0] cx_out_imag_1_21_1_sva_dfm;
  reg cx_out_imag_1_0_sva_dfm;
  reg [20:0] cx_out_imag_2_21_1_sva_dfm;
  reg cx_out_imag_2_0_sva_dfm;
  reg [20:0] cx_out_imag_3_21_1_sva_dfm;
  reg cx_out_imag_3_0_sva_dfm;
  reg [20:0] cx_out_imag_4_21_1_sva_dfm;
  reg cx_out_imag_4_0_sva_dfm;
  reg [20:0] cx_out_imag_5_21_1_sva_dfm;
  reg cx_out_imag_5_0_sva_dfm;
  reg [20:0] cx_out_imag_6_21_1_sva_dfm;
  reg cx_out_imag_6_0_sva_dfm;
  reg [20:0] cx_out_imag_7_21_1_sva_dfm;
  reg cx_out_imag_7_0_sva_dfm;
  reg [20:0] but_5_conc_8_ncse_21_1_sva_1;
  reg but_5_conc_8_ncse_0_sva_1;
  reg [20:0] but_5_conc_9_ncse_21_1_sva_1;
  reg but_5_conc_9_ncse_0_sva_1;
  reg [20:0] but_5_conc_10_ncse_21_1_sva_1;
  reg but_5_conc_10_ncse_0_sva_1;
  reg [20:0] but_5_conc_11_ncse_21_1_sva_1;
  reg but_5_conc_11_ncse_0_sva_1;
  reg [27:0] but_9_mul_psp_sva_1;
  wire signed [28:0] nl_but_9_mul_psp_sva_1;
  reg [27:0] but_9_mul_1_psp_sva_1;
  wire signed [28:0] nl_but_9_mul_1_psp_sva_1;
  reg [27:0] but_9_mul_2_psp_sva_1;
  wire signed [28:0] nl_but_9_mul_2_psp_sva_1;
  reg [27:0] but_9_mul_3_psp_sva_1;
  wire signed [28:0] nl_but_9_mul_3_psp_sva_1;
  reg [27:0] but_11_mul_psp_sva_1;
  wire signed [28:0] nl_but_11_mul_psp_sva_1;
  reg [27:0] but_11_mul_1_psp_sva_1;
  wire signed [28:0] nl_but_11_mul_1_psp_sva_1;
  reg while_if_if_2_mux_3_itm_1_1;
  reg [20:0] while_if_if_2_mux_4_itm_1_1;
  reg while_if_if_2_mux_5_itm_1_1;
  reg but_5_slc_but_5_acc_psp_23_40_itm_1;
  reg but_5_slc_but_5_acc_12_psp_23_40_itm_1;
  reg but_6_slc_but_6_acc_14_psp_23_2_itm_1;
  reg [20:0] but_10_but_6_or_itm_1;
  reg but_10_but_6_or_1_itm_1;
  reg but_6_slc_but_6_acc_13_psp_23_2_itm_1;
  reg [20:0] but_10_but_6_or_2_itm_1;
  reg but_10_but_6_or_3_itm_1;
  reg but_5_slc_but_5_acc_13_psp_23_40_itm_1;
  reg but_5_slc_but_5_acc_14_psp_23_40_itm_1;
  reg while_if_while_if_if_and_itm_1;
  reg but_8_acc_psp_lpi_1_dfm_23;
  reg but_8_acc_12_psp_lpi_1_dfm_23;
  reg but_8_acc_13_psp_lpi_1_dfm_23;
  reg but_8_acc_14_psp_lpi_1_dfm_23;
  reg but_9_acc_2_psp_1_lpi_1_dfm_24;
  reg but_9_acc_5_psp_1_lpi_1_dfm_24;
  reg but_9_acc_8_psp_1_lpi_1_dfm_24;
  reg but_9_acc_11_psp_1_lpi_1_dfm_24;
  reg but_10_acc_psp_lpi_1_dfm_23;
  reg but_10_acc_12_psp_lpi_1_dfm_23;
  reg but_10_acc_13_psp_lpi_1_dfm_23;
  reg but_10_acc_14_psp_lpi_1_dfm_23;
  reg but_11_acc_2_psp_1_lpi_1_dfm_24;
  reg but_11_acc_5_psp_1_lpi_1_dfm_24;
  reg but_11_acc_8_psp_1_lpi_1_dfm_24;
  reg but_11_acc_11_psp_1_lpi_1_dfm_24;
  reg while_if_if_2_conc_itm_1_22_1;
  reg [20:0] while_if_if_2_conc_itm_1_21_1_1;
  reg while_if_if_2_conc_itm_1_0_1;
  wire data_valid_sink_mx0c1;
  wire data_req_source_mx0c0;
  wire cx_out_imag_7_0_sva_dfm_mx0;
  wire [20:0] cx_out_imag_7_21_1_sva_dfm_mx0;
  wire cx_out_imag_5_0_sva_dfm_mx0;
  wire [20:0] cx_out_imag_5_21_1_sva_dfm_mx0;
  wire cx_out_imag_3_0_sva_dfm_mx0;
  wire [20:0] cx_out_imag_3_21_1_sva_dfm_mx0;
  wire cx_out_imag_1_0_sva_dfm_mx0;
  wire [20:0] cx_out_imag_1_21_1_sva_dfm_mx0;
  wire cx_out_real_7_0_sva_dfm_mx0;
  wire [20:0] cx_out_real_7_21_1_sva_dfm_mx0;
  wire cx_out_real_5_0_sva_dfm_mx0;
  wire [20:0] cx_out_real_5_21_1_sva_dfm_mx0;
  wire cx_out_real_3_0_sva_dfm_mx0;
  wire [20:0] cx_out_real_3_21_1_sva_dfm_mx0;
  wire cx_out_real_1_0_sva_dfm_mx0;
  wire [20:0] cx_out_real_1_21_1_sva_dfm_mx0;
  wire but_11_acc_11_psp_1_lpi_1_dfm_24_mx0;
  wire but_11_acc_8_psp_1_lpi_1_dfm_24_mx0;
  wire but_11_acc_5_psp_1_lpi_1_dfm_24_mx0;
  wire but_11_acc_2_psp_1_lpi_1_dfm_24_mx0;
  wire but_9_acc_11_psp_1_lpi_1_dfm_24_mx0;
  wire but_9_acc_8_psp_1_lpi_1_dfm_24_mx0;
  wire but_9_acc_5_psp_1_lpi_1_dfm_24_mx0;
  wire but_9_acc_2_psp_1_lpi_1_dfm_24_mx0;
  wire but_11_nor_ovfl_3_sva_1;
  wire but_11_and_unfl_3_sva_1;
  wire but_9_nor_ovfl_1_sva_1;
  wire but_9_and_unfl_1_sva_1;
  wire but_9_nor_ovfl_3_sva_1;
  wire but_9_and_unfl_3_sva_1;
  wire but_11_nor_ovfl_1_sva_1;
  wire but_11_and_unfl_1_sva_1;
  wire but_11_nor_ovfl_2_sva_1;
  wire but_11_and_unfl_2_sva_1;
  wire but_9_nor_ovfl_sva_1;
  wire but_9_and_unfl_sva_1;
  wire but_9_nor_ovfl_2_sva_1;
  wire but_9_and_unfl_2_sva_1;
  wire but_11_nor_ovfl_sva_1;
  wire but_11_and_unfl_sva_1;
  wire but_8_nor_ovfl_1_sva_1;
  wire but_8_and_unfl_1_sva_1;
  wire but_10_nor_ovfl_3_sva_1;
  wire but_10_and_unfl_3_sva_1;
  wire but_10_nor_ovfl_1_sva_1;
  wire but_10_and_unfl_1_sva_1;
  wire but_8_nor_ovfl_3_sva_1;
  wire but_8_and_unfl_3_sva_1;
  wire but_8_nor_ovfl_sva_1;
  wire but_8_and_unfl_sva_1;
  wire but_10_nor_ovfl_2_sva_1;
  wire but_10_and_unfl_2_sva_1;
  wire but_10_nor_ovfl_sva_1;
  wire but_10_and_unfl_sva_1;
  wire but_8_nor_ovfl_2_sva_1;
  wire but_8_and_unfl_2_sva_1;
  wire but_7_nor_ovfl_3_sva_1;
  wire but_7_and_unfl_3_sva_1;
  wire but_7_nor_ovfl_2_sva_1;
  wire but_7_and_unfl_2_sva_1;
  wire but_7_nor_ovfl_1_sva_1;
  wire but_7_and_unfl_1_sva_1;
  wire but_7_nor_ovfl_sva_1;
  wire but_7_and_unfl_sva_1;
  wire but_5_nor_ovfl_3_sva_1;
  wire but_5_and_unfl_3_sva_1;
  wire but_5_nor_ovfl_2_sva_1;
  wire but_5_and_unfl_2_sva_1;
  wire but_5_nor_ovfl_1_sva_1;
  wire but_5_and_unfl_1_sva_1;
  wire but_5_nor_ovfl_sva_1;
  wire but_5_and_unfl_sva_1;
  wire but_6_nor_ovfl_2_sva_1;
  wire but_6_and_unfl_2_sva_1;
  wire but_6_nor_ovfl_3_sva_1;
  wire but_6_and_unfl_3_sva_1;
  wire but_6_nor_ovfl_1_sva_1;
  wire but_6_and_unfl_1_sva_1;
  wire but_6_nor_ovfl_sva_1;
  wire but_6_and_unfl_sva_1;
  wire but_4_nor_ovfl_3_sva_1;
  wire but_4_and_unfl_3_sva_1;
  wire but_4_nor_ovfl_2_sva_1;
  wire but_4_and_unfl_2_sva_1;
  wire but_4_nor_ovfl_1_sva_1;
  wire but_4_and_unfl_1_sva_1;
  wire but_4_nor_ovfl_sva_1;
  wire but_4_and_unfl_sva_1;
  wire but_3_nor_ovfl_1_sva_1;
  wire but_3_and_unfl_1_sva_1;
  wire but_3_nor_ovfl_sva_1;
  wire but_3_and_unfl_sva_1;
  wire but_2_nor_ovfl_3_sva_1;
  wire but_2_and_unfl_3_sva_1;
  wire but_2_nor_ovfl_2_sva_1;
  wire but_2_and_unfl_2_sva_1;
  wire but_2_nor_ovfl_1_sva_1;
  wire but_2_and_unfl_1_sva_1;
  wire but_2_nor_ovfl_sva_1;
  wire but_2_and_unfl_sva_1;
  wire but_1_nor_ovfl_1_sva_1;
  wire but_1_and_unfl_1_sva_1;
  wire but_1_nor_ovfl_sva_1;
  wire but_1_and_unfl_sva_1;
  wire but_nor_ovfl_3_sva_1;
  wire but_and_unfl_3_sva_1;
  wire but_nor_ovfl_2_sva_1;
  wire but_and_unfl_2_sva_1;
  wire but_nor_ovfl_1_sva_1;
  wire but_and_unfl_1_sva_1;
  wire but_nor_ovfl_sva_1;
  wire but_and_unfl_sva_1;
  wire [20:0] but_7_conc_76_21_1;
  wire but_7_conc_76_0;
  wire [20:0] but_7_conc_78_21_1;
  wire but_7_conc_78_0;
  wire but_8_or_cse;
  wire [20:0] but_8_nor_18_cse;
  wire but_8_nor_19_cse;
  wire [20:0] but_8_nor_15_cse;
  wire but_8_nor_16_cse;
  wire [20:0] but_8_nor_12_cse;
  wire but_8_nor_13_cse;
  wire [20:0] but_8_nor_9_cse;
  wire but_8_nor_10_cse;

  wire[20:0] but_7_but_7_nor_7_nl;
  wire[20:0] but_7_nor_15_nl;
  wire but_7_but_7_nor_8_nl;
  wire[20:0] but_7_but_7_nor_10_nl;
  wire[20:0] but_7_nor_18_nl;
  wire but_7_but_7_nor_11_nl;
  wire[20:0] but_5_nor_18_nl;
  wire[20:0] but_5_nor_15_nl;
  wire[20:0] but_5_nor_12_nl;
  wire[20:0] but_5_nor_9_nl;
  wire[20:0] but_10_nor_12_nl;
  wire[20:0] but_10_nor_18_nl;
  wire[20:0] but_10_nor_9_nl;
  wire[20:0] but_10_nor_15_nl;
  wire while_if_mux_2_nl;
  wire[20:0] but_4_nor_18_nl;
  wire[20:0] but_4_nor_15_nl;
  wire[20:0] but_6_nor_15_nl;
  wire[20:0] but_6_nor_18_nl;
  wire[20:0] but_4_nor_12_nl;
  wire[20:0] but_6_nor_12_nl;
  wire[20:0] but_4_nor_9_nl;
  wire[20:0] but_6_nor_9_nl;
  wire[20:0] but_7_but_3_or_2_nl;
  wire but_7_but_3_or_3_nl;
  wire[20:0] but_2_nor_18_nl;
  wire[20:0] but_2_nor_15_nl;
  wire[20:0] but_7_but_3_or_nl;
  wire but_7_but_3_or_1_nl;
  wire[20:0] but_5_but_1_or_2_nl;
  wire but_5_but_1_or_3_nl;
  wire[20:0] but_nor_18_nl;
  wire[20:0] but_nor_15_nl;
  wire[20:0] but_5_but_1_or_nl;
  wire but_5_but_1_or_1_nl;
  wire but_11_but_11_nor_12_nl;
  wire[20:0] but_11_but_11_nor_10_nl;
  wire[20:0] but_11_nor_18_nl;
  wire but_9_but_9_nor_12_nl;
  wire[20:0] but_9_but_9_nor_10_nl;
  wire[20:0] but_9_nor_18_nl;
  wire but_11_but_11_nor_13_nl;
  wire[20:0] but_11_but_11_nor_4_nl;
  wire[20:0] but_11_nor_12_nl;
  wire but_9_but_9_nor_13_nl;
  wire[20:0] but_9_but_9_nor_4_nl;
  wire[20:0] but_9_nor_12_nl;
  wire but_11_but_11_nor_14_nl;
  wire[20:0] but_11_but_11_nor_7_nl;
  wire[20:0] but_11_nor_15_nl;
  wire but_9_but_9_nor_14_nl;
  wire[20:0] but_9_but_9_nor_7_nl;
  wire[20:0] but_9_nor_15_nl;
  wire but_11_but_11_nor_15_nl;
  wire[20:0] but_11_but_11_nor_1_nl;
  wire[20:0] but_11_nor_9_nl;
  wire but_9_but_9_nor_15_nl;
  wire[20:0] but_9_but_9_nor_1_nl;
  wire[20:0] but_9_nor_9_nl;
  wire but_11_and_15_nl;
  wire but_9_and_5_nl;
  wire but_9_and_15_nl;
  wire but_11_and_5_nl;
  wire but_11_and_10_nl;
  wire but_9_and_nl;
  wire but_9_and_10_nl;
  wire but_11_and_nl;
  wire[28:0] but_11_acc_15_nl;
  wire[29:0] nl_but_11_acc_15_nl;
  wire[28:0] but_11_acc_14_nl;
  wire[28:0] but_11_acc_12_nl;
  wire[28:0] but_9_acc_15_nl;
  wire[29:0] nl_but_9_acc_15_nl;
  wire[28:0] but_9_acc_14_nl;
  wire[28:0] but_9_acc_12_nl;
  wire[20:0] but_3_nor_12_nl;
  wire[20:0] but_3_nor_9_nl;
  wire[20:0] but_1_nor_12_nl;
  wire[20:0] but_1_nor_9_nl;
  wire[20:0] but_7_nor_12_nl;
  wire[20:0] but_7_nor_9_nl;
  wire[20:0] but_2_nor_12_nl;
  wire[20:0] but_2_nor_9_nl;
  wire[20:0] but_nor_12_nl;
  wire[20:0] but_nor_9_nl;
  wire[24:0] acc_nl;
  wire[25:0] nl_acc_nl;
  wire but_8_mux_28_nl;
  wire[20:0] but_8_mux_29_nl;
  wire but_8_mux_30_nl;
  wire but_8_mux_31_nl;
  wire[20:0] but_8_mux_32_nl;
  wire but_8_mux_33_nl;
  wire[24:0] acc_1_nl;
  wire[25:0] nl_acc_1_nl;
  wire but_8_mux_34_nl;
  wire[20:0] but_8_mux_35_nl;
  wire but_8_mux_36_nl;
  wire but_8_mux_37_nl;
  wire[20:0] but_8_mux_38_nl;
  wire but_8_mux_39_nl;
  wire[24:0] acc_2_nl;
  wire[25:0] nl_acc_2_nl;
  wire but_8_mux_40_nl;
  wire[20:0] but_8_mux_41_nl;
  wire but_8_mux_42_nl;
  wire but_8_mux_43_nl;
  wire[20:0] but_8_mux_44_nl;
  wire but_8_mux_45_nl;
  wire[24:0] acc_3_nl;
  wire[25:0] nl_acc_3_nl;
  wire but_8_mux_46_nl;
  wire[20:0] but_8_mux_47_nl;
  wire but_8_mux_48_nl;
  wire but_8_mux_49_nl;
  wire[20:0] but_8_mux_50_nl;
  wire but_8_mux_51_nl;

  // Interconnect Declarations for Component Instantiations 
  assign out_real = {while_if_if_2_conc_itm_1_22 , while_if_if_2_conc_itm_1_21_1
      , while_if_if_2_conc_itm_1_0};
  assign out_img = {while_if_if_2_mux_3_itm_1 , while_if_if_2_mux_4_itm_1 , while_if_if_2_mux_5_itm_1};
  assign while_if_aif_1_while_if_aelse_1_nand_cse = ~(j_sva_3 & while_if_if_nor_cse_sva_1);
  assign but_8_nor_13_cse = ~((z_out[0]) | but_8_nor_ovfl_1_sva_1);
  assign but_8_nor_19_cse = ~((z_out_1[0]) | but_8_nor_ovfl_3_sva_1);
  assign but_8_nor_12_cse = ~(MUX_v_21_2_2((z_out[21:1]), 21'b111111111111111111111,
      but_8_nor_ovfl_1_sva_1));
  assign but_8_nor_18_cse = ~(MUX_v_21_2_2((z_out_1[21:1]), 21'b111111111111111111111,
      but_8_nor_ovfl_3_sva_1));
  assign but_8_nor_10_cse = ~((z_out_2[0]) | but_8_nor_ovfl_sva_1);
  assign but_8_nor_16_cse = ~((z_out_3[0]) | but_8_nor_ovfl_2_sva_1);
  assign but_8_nor_9_cse = ~(MUX_v_21_2_2((z_out_2[21:1]), 21'b111111111111111111111,
      but_8_nor_ovfl_sva_1));
  assign but_8_nor_15_cse = ~(MUX_v_21_2_2((z_out_3[21:1]), 21'b111111111111111111111,
      but_8_nor_ovfl_2_sva_1));
  assign while_if_land_2_lpi_1_dfm_1 = j_sva_dfm_mx0_3 & (~((j_sva_dfm_mx0_31_4!=28'b0000000000000000000000000000)
      | (j_sva_dfm_mx0_2_0!=3'b000))) & i_sva_dfm_mx0_3 & (~((i_sva_dfm_mx0_31_4!=28'b0000000000000000000000000000)
      | (i_sva_dfm_mx0_2_0!=3'b000)));
  assign nl_while_if_if_1_acc_tmp = ({i_sva_31_4 , i_sva_3 , i_sva_2_0}) + 32'b00000000000000000000000000000001;
  assign while_if_if_1_acc_tmp = nl_while_if_if_1_acc_tmp[31:0];
  assign or_12_ssc = and_dcpl_14 | (~ data_valid_source);
  assign i_sva_dfm_mx0_31_4 = MUX_v_28_2_2((while_if_if_1_acc_tmp[31:4]), i_sva_31_4,
      or_12_ssc);
  assign i_sva_dfm_mx0_3 = MUX_s_1_2_2((while_if_if_1_acc_tmp[3]), i_sva_3, or_12_ssc);
  assign i_sva_dfm_mx0_2_0 = MUX_v_3_2_2((while_if_if_1_acc_tmp[2:0]), i_sva_2_0,
      or_12_ssc);
  assign i_or_cse = or_12_ssc | or_dcpl_10;
  assign i_sva_31_4_mx0 = MUX_v_28_2_2((while_if_if_1_acc_tmp[31:4]), i_sva_31_4,
      i_or_cse);
  assign i_sva_2_0_mx0 = MUX_v_3_2_2((while_if_if_1_acc_tmp[2:0]), i_sva_2_0, i_or_cse);
  assign nl_while_if_if_2_acc_tmp = ({j_sva_31_4 , j_sva_3 , j_sva_2_0}) + 32'b00000000000000000000000000000001;
  assign while_if_if_2_acc_tmp = nl_while_if_if_2_acc_tmp[31:0];
  assign nand_10_ssc = ~(while_if_aif_1_while_if_aelse_1_nand_cse & data_req_sink);
  assign j_sva_dfm_mx0_31_4 = MUX_v_28_2_2((while_if_if_2_acc_tmp[31:4]), j_sva_31_4,
      nand_10_ssc);
  assign j_sva_dfm_mx0_3 = MUX_s_1_2_2((while_if_if_2_acc_tmp[3]), j_sva_3, nand_10_ssc);
  assign j_sva_dfm_mx0_2_0 = MUX_v_3_2_2((while_if_if_2_acc_tmp[2:0]), j_sva_2_0,
      nand_10_ssc);
  assign j_or_cse = nand_10_ssc | or_dcpl_10;
  assign j_sva_31_4_mx0 = MUX_v_28_2_2((while_if_if_2_acc_tmp[31:4]), j_sva_31_4,
      j_or_cse);
  assign while_if_while_if_and_1_mx0w0 = j_sva_dfm_mx0_3 & (~ while_if_land_2_lpi_1_dfm_1);
  assign j_sva_2_0_mx0 = MUX_v_3_2_2((while_if_if_2_acc_tmp[2:0]), j_sva_2_0, j_or_cse);
  assign while_if_if_nor_cse_sva_1_1 = ~((j_sva_31_4_mx0!=28'b0000000000000000000000000000)
      | (j_sva_2_0_mx0!=3'b000));
  assign but_11_but_11_nor_12_nl = ~((~((but_11_acc_11_psp_1_sva_1[0]) | but_11_nor_ovfl_3_sva_1))
      | but_11_and_unfl_3_sva_1);
  assign cx_out_imag_7_0_sva_dfm_mx0 = MUX_s_1_2_2(but_11_but_11_nor_12_nl, cx_out_imag_7_0_sva_dfm,
      or_dcpl_12);
  assign but_11_nor_18_nl = ~(MUX_v_21_2_2((but_11_acc_11_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_11_nor_ovfl_3_sva_1));
  assign but_11_but_11_nor_10_nl = ~(MUX_v_21_2_2(but_11_nor_18_nl, 21'b111111111111111111111,
      but_11_and_unfl_3_sva_1));
  assign cx_out_imag_7_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_11_but_11_nor_10_nl, cx_out_imag_7_21_1_sva_dfm,
      or_dcpl_12);
  assign but_9_but_9_nor_12_nl = ~((~((but_9_acc_11_psp_1_sva_1[0]) | but_9_nor_ovfl_3_sva_1))
      | but_9_and_unfl_3_sva_1);
  assign cx_out_imag_5_0_sva_dfm_mx0 = MUX_s_1_2_2(but_9_but_9_nor_12_nl, cx_out_imag_5_0_sva_dfm,
      or_dcpl_12);
  assign but_9_nor_18_nl = ~(MUX_v_21_2_2((but_9_acc_11_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_9_nor_ovfl_3_sva_1));
  assign but_9_but_9_nor_10_nl = ~(MUX_v_21_2_2(but_9_nor_18_nl, 21'b111111111111111111111,
      but_9_and_unfl_3_sva_1));
  assign cx_out_imag_5_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_9_but_9_nor_10_nl, cx_out_imag_5_21_1_sva_dfm,
      or_dcpl_12);
  assign but_11_but_11_nor_13_nl = ~((~((but_11_acc_5_psp_1_sva_1[0]) | but_11_nor_ovfl_1_sva_1))
      | but_11_and_unfl_1_sva_1);
  assign cx_out_imag_3_0_sva_dfm_mx0 = MUX_s_1_2_2(but_11_but_11_nor_13_nl, cx_out_imag_3_0_sva_dfm,
      or_dcpl_12);
  assign but_11_nor_12_nl = ~(MUX_v_21_2_2((but_11_acc_5_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_11_nor_ovfl_1_sva_1));
  assign but_11_but_11_nor_4_nl = ~(MUX_v_21_2_2(but_11_nor_12_nl, 21'b111111111111111111111,
      but_11_and_unfl_1_sva_1));
  assign cx_out_imag_3_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_11_but_11_nor_4_nl, cx_out_imag_3_21_1_sva_dfm,
      or_dcpl_12);
  assign but_9_but_9_nor_13_nl = ~((~((but_9_acc_5_psp_1_sva_1[0]) | but_9_nor_ovfl_1_sva_1))
      | but_9_and_unfl_1_sva_1);
  assign cx_out_imag_1_0_sva_dfm_mx0 = MUX_s_1_2_2(but_9_but_9_nor_13_nl, cx_out_imag_1_0_sva_dfm,
      or_dcpl_12);
  assign but_9_nor_12_nl = ~(MUX_v_21_2_2((but_9_acc_5_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_9_nor_ovfl_1_sva_1));
  assign but_9_but_9_nor_4_nl = ~(MUX_v_21_2_2(but_9_nor_12_nl, 21'b111111111111111111111,
      but_9_and_unfl_1_sva_1));
  assign cx_out_imag_1_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_9_but_9_nor_4_nl, cx_out_imag_1_21_1_sva_dfm,
      or_dcpl_12);
  assign but_11_but_11_nor_14_nl = ~((~((but_11_acc_8_psp_1_sva_1[0]) | but_11_nor_ovfl_2_sva_1))
      | but_11_and_unfl_2_sva_1);
  assign cx_out_real_7_0_sva_dfm_mx0 = MUX_s_1_2_2(but_11_but_11_nor_14_nl, cx_out_real_7_0_sva_dfm,
      or_dcpl_12);
  assign but_11_nor_15_nl = ~(MUX_v_21_2_2((but_11_acc_8_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_11_nor_ovfl_2_sva_1));
  assign but_11_but_11_nor_7_nl = ~(MUX_v_21_2_2(but_11_nor_15_nl, 21'b111111111111111111111,
      but_11_and_unfl_2_sva_1));
  assign cx_out_real_7_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_11_but_11_nor_7_nl, cx_out_real_7_21_1_sva_dfm,
      or_dcpl_12);
  assign but_9_but_9_nor_14_nl = ~((~((but_9_acc_8_psp_1_sva_1[0]) | but_9_nor_ovfl_2_sva_1))
      | but_9_and_unfl_2_sva_1);
  assign cx_out_real_5_0_sva_dfm_mx0 = MUX_s_1_2_2(but_9_but_9_nor_14_nl, cx_out_real_5_0_sva_dfm,
      or_dcpl_12);
  assign but_9_nor_15_nl = ~(MUX_v_21_2_2((but_9_acc_8_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_9_nor_ovfl_2_sva_1));
  assign but_9_but_9_nor_7_nl = ~(MUX_v_21_2_2(but_9_nor_15_nl, 21'b111111111111111111111,
      but_9_and_unfl_2_sva_1));
  assign cx_out_real_5_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_9_but_9_nor_7_nl, cx_out_real_5_21_1_sva_dfm,
      or_dcpl_12);
  assign but_11_but_11_nor_15_nl = ~((~((but_11_acc_2_psp_1_sva_1[0]) | but_11_nor_ovfl_sva_1))
      | but_11_and_unfl_sva_1);
  assign cx_out_real_3_0_sva_dfm_mx0 = MUX_s_1_2_2(but_11_but_11_nor_15_nl, cx_out_real_3_0_sva_dfm,
      or_dcpl_12);
  assign but_11_nor_9_nl = ~(MUX_v_21_2_2((but_11_acc_2_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_11_nor_ovfl_sva_1));
  assign but_11_but_11_nor_1_nl = ~(MUX_v_21_2_2(but_11_nor_9_nl, 21'b111111111111111111111,
      but_11_and_unfl_sva_1));
  assign cx_out_real_3_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_11_but_11_nor_1_nl, cx_out_real_3_21_1_sva_dfm,
      or_dcpl_12);
  assign but_9_but_9_nor_15_nl = ~((~((but_9_acc_2_psp_1_sva_1[0]) | but_9_nor_ovfl_sva_1))
      | but_9_and_unfl_sva_1);
  assign cx_out_real_1_0_sva_dfm_mx0 = MUX_s_1_2_2(but_9_but_9_nor_15_nl, cx_out_real_1_0_sva_dfm,
      or_dcpl_12);
  assign but_9_nor_9_nl = ~(MUX_v_21_2_2((but_9_acc_2_psp_1_sva_1[21:1]), 21'b111111111111111111111,
      but_9_nor_ovfl_sva_1));
  assign but_9_but_9_nor_1_nl = ~(MUX_v_21_2_2(but_9_nor_9_nl, 21'b111111111111111111111,
      but_9_and_unfl_sva_1));
  assign cx_out_real_1_21_1_sva_dfm_mx0 = MUX_v_21_2_2(but_9_but_9_nor_1_nl, cx_out_real_1_21_1_sva_dfm,
      or_dcpl_12);
  assign but_11_acc_11_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_11_acc_11_psp_1_sva_1[24]),
      but_11_acc_11_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_11_acc_8_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_11_acc_8_psp_1_sva_1[24]),
      but_11_acc_8_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_11_acc_5_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_11_acc_5_psp_1_sva_1[24]),
      but_11_acc_5_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_11_acc_2_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_11_acc_2_psp_1_sva_1[24]),
      but_11_acc_2_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_9_acc_11_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_9_acc_11_psp_1_sva_1[24]),
      but_9_acc_11_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_9_acc_8_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_9_acc_8_psp_1_sva_1[24]),
      but_9_acc_8_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_9_acc_5_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_9_acc_5_psp_1_sva_1[24]),
      but_9_acc_5_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_9_acc_2_psp_1_lpi_1_dfm_24_mx0 = MUX_s_1_2_2((but_9_acc_2_psp_1_sva_1[24]),
      but_9_acc_2_psp_1_lpi_1_dfm_24, or_dcpl_12);
  assign but_11_and_15_nl = (but_11_acc_9_psp_sva_1[4]) & ((but_11_acc_9_psp_sva_1[0])
      | (but_11_acc_9_psp_sva_1[1]) | (but_11_acc_9_psp_sva_1[2]) | (but_11_acc_9_psp_sva_1[3])
      | (~ (but_11_acc_9_psp_sva_1[29])));
  assign nl_but_11_acc_11_psp_1_sva_1 = (but_11_acc_9_psp_sva_1[29:5]) + conv_u2s_1_25(but_11_and_15_nl);
  assign but_11_acc_11_psp_1_sva_1 = nl_but_11_acc_11_psp_1_sva_1[24:0];
  assign but_11_nor_ovfl_3_sva_1 = ~((but_11_acc_11_psp_1_sva_1[24]) | (~((but_11_acc_11_psp_1_sva_1[23:22]!=2'b00))));
  assign but_11_and_unfl_3_sva_1 = (but_11_acc_11_psp_1_sva_1[24]) & (~((but_11_acc_11_psp_1_sva_1[23:22]==2'b11)));
  assign but_9_and_5_nl = (but_9_acc_3_psp_sva_1[4]) & ((but_9_acc_3_psp_sva_1[0])
      | (but_9_acc_3_psp_sva_1[1]) | (but_9_acc_3_psp_sva_1[2]) | (but_9_acc_3_psp_sva_1[3])
      | (~ (but_9_acc_3_psp_sva_1[29])));
  assign nl_but_9_acc_5_psp_1_sva_1 = (but_9_acc_3_psp_sva_1[29:5]) + conv_u2s_1_25(but_9_and_5_nl);
  assign but_9_acc_5_psp_1_sva_1 = nl_but_9_acc_5_psp_1_sva_1[24:0];
  assign but_9_nor_ovfl_1_sva_1 = ~((but_9_acc_5_psp_1_sva_1[24]) | (~((but_9_acc_5_psp_1_sva_1[23:22]!=2'b00))));
  assign but_9_and_unfl_1_sva_1 = (but_9_acc_5_psp_1_sva_1[24]) & (~((but_9_acc_5_psp_1_sva_1[23:22]==2'b11)));
  assign but_9_and_15_nl = (but_9_acc_9_psp_sva_1[4]) & ((but_9_acc_9_psp_sva_1[0])
      | (but_9_acc_9_psp_sva_1[1]) | (but_9_acc_9_psp_sva_1[2]) | (but_9_acc_9_psp_sva_1[3])
      | (~ (but_9_acc_9_psp_sva_1[29])));
  assign nl_but_9_acc_11_psp_1_sva_1 = (but_9_acc_9_psp_sva_1[29:5]) + conv_u2s_1_25(but_9_and_15_nl);
  assign but_9_acc_11_psp_1_sva_1 = nl_but_9_acc_11_psp_1_sva_1[24:0];
  assign but_9_nor_ovfl_3_sva_1 = ~((but_9_acc_11_psp_1_sva_1[24]) | (~((but_9_acc_11_psp_1_sva_1[23:22]!=2'b00))));
  assign but_9_and_unfl_3_sva_1 = (but_9_acc_11_psp_1_sva_1[24]) & (~((but_9_acc_11_psp_1_sva_1[23:22]==2'b11)));
  assign but_11_and_5_nl = (but_11_acc_3_psp_sva_1[4]) & ((but_11_acc_3_psp_sva_1[0])
      | (but_11_acc_3_psp_sva_1[1]) | (but_11_acc_3_psp_sva_1[2]) | (but_11_acc_3_psp_sva_1[3])
      | (~ (but_11_acc_3_psp_sva_1[29])));
  assign nl_but_11_acc_5_psp_1_sva_1 = (but_11_acc_3_psp_sva_1[29:5]) + conv_u2s_1_25(but_11_and_5_nl);
  assign but_11_acc_5_psp_1_sva_1 = nl_but_11_acc_5_psp_1_sva_1[24:0];
  assign but_11_nor_ovfl_1_sva_1 = ~((but_11_acc_5_psp_1_sva_1[24]) | (~((but_11_acc_5_psp_1_sva_1[23:22]!=2'b00))));
  assign but_11_and_unfl_1_sva_1 = (but_11_acc_5_psp_1_sva_1[24]) & (~((but_11_acc_5_psp_1_sva_1[23:22]==2'b11)));
  assign but_11_and_10_nl = (but_11_acc_6_psp_sva_1[4]) & ((but_11_acc_6_psp_sva_1[0])
      | (but_11_acc_6_psp_sva_1[1]) | (but_11_acc_6_psp_sva_1[2]) | (but_11_acc_6_psp_sva_1[3])
      | (~ (but_11_acc_6_psp_sva_1[29])));
  assign nl_but_11_acc_8_psp_1_sva_1 = (but_11_acc_6_psp_sva_1[29:5]) + conv_u2s_1_25(but_11_and_10_nl);
  assign but_11_acc_8_psp_1_sva_1 = nl_but_11_acc_8_psp_1_sva_1[24:0];
  assign but_11_nor_ovfl_2_sva_1 = ~((but_11_acc_8_psp_1_sva_1[24]) | (~((but_11_acc_8_psp_1_sva_1[23:22]!=2'b00))));
  assign but_11_and_unfl_2_sva_1 = (but_11_acc_8_psp_1_sva_1[24]) & (~((but_11_acc_8_psp_1_sva_1[23:22]==2'b11)));
  assign but_9_and_nl = (but_9_acc_psp_sva_1[4]) & ((but_9_acc_psp_sva_1[0]) | (but_9_acc_psp_sva_1[1])
      | (but_9_acc_psp_sva_1[2]) | (but_9_acc_psp_sva_1[3]) | (~ (but_9_acc_psp_sva_1[29])));
  assign nl_but_9_acc_2_psp_1_sva_1 = (but_9_acc_psp_sva_1[29:5]) + conv_u2s_1_25(but_9_and_nl);
  assign but_9_acc_2_psp_1_sva_1 = nl_but_9_acc_2_psp_1_sva_1[24:0];
  assign but_9_nor_ovfl_sva_1 = ~((but_9_acc_2_psp_1_sva_1[24]) | (~((but_9_acc_2_psp_1_sva_1[23:22]!=2'b00))));
  assign but_9_and_unfl_sva_1 = (but_9_acc_2_psp_1_sva_1[24]) & (~((but_9_acc_2_psp_1_sva_1[23:22]==2'b11)));
  assign but_9_and_10_nl = (but_9_acc_6_psp_sva_1[4]) & ((but_9_acc_6_psp_sva_1[0])
      | (but_9_acc_6_psp_sva_1[1]) | (but_9_acc_6_psp_sva_1[2]) | (but_9_acc_6_psp_sva_1[3])
      | (~ (but_9_acc_6_psp_sva_1[29])));
  assign nl_but_9_acc_8_psp_1_sva_1 = (but_9_acc_6_psp_sva_1[29:5]) + conv_u2s_1_25(but_9_and_10_nl);
  assign but_9_acc_8_psp_1_sva_1 = nl_but_9_acc_8_psp_1_sva_1[24:0];
  assign but_9_nor_ovfl_2_sva_1 = ~((but_9_acc_8_psp_1_sva_1[24]) | (~((but_9_acc_8_psp_1_sva_1[23:22]!=2'b00))));
  assign but_9_and_unfl_2_sva_1 = (but_9_acc_8_psp_1_sva_1[24]) & (~((but_9_acc_8_psp_1_sva_1[23:22]==2'b11)));
  assign but_11_and_nl = (but_11_acc_psp_sva_1[4]) & ((but_11_acc_psp_sva_1[0]) |
      (but_11_acc_psp_sva_1[1]) | (but_11_acc_psp_sva_1[2]) | (but_11_acc_psp_sva_1[3])
      | (~ (but_11_acc_psp_sva_1[29])));
  assign nl_but_11_acc_2_psp_1_sva_1 = (but_11_acc_psp_sva_1[29:5]) + conv_u2s_1_25(but_11_and_nl);
  assign but_11_acc_2_psp_1_sva_1 = nl_but_11_acc_2_psp_1_sva_1[24:0];
  assign but_11_nor_ovfl_sva_1 = ~((but_11_acc_2_psp_1_sva_1[24]) | (~((but_11_acc_2_psp_1_sva_1[23:22]!=2'b00))));
  assign but_11_and_unfl_sva_1 = (but_11_acc_2_psp_1_sva_1[24]) & (~((but_11_acc_2_psp_1_sva_1[23:22]==2'b11)));
  assign nl_but_11_acc_15_nl = conv_s2s_28_29(~ but_11_mul_psp_sva_1) + conv_s2s_28_29(~
      but_11_mul_1_psp_sva_1) + 29'b00000000000000000000000000001;
  assign but_11_acc_15_nl = nl_but_11_acc_15_nl[28:0];
  assign nl_but_11_acc_9_psp_sva_1 = conv_s2s_29_30(but_11_acc_15_nl) + conv_s2s_28_30({but_5_slc_but_5_acc_14_psp_23_40_itm_1
      , but_5_conc_11_ncse_21_1_sva_1 , but_5_conc_11_ncse_0_sva_1 , 5'b00000}) +
      30'b000000000000000000000000000001;
  assign but_11_acc_9_psp_sva_1 = nl_but_11_acc_9_psp_sva_1[29:0];
  assign but_11_acc_14_nl = $signed(but_11_mul_1_psp_sva_1) - $signed(but_11_mul_psp_sva_1);
  assign nl_but_11_acc_6_psp_sva_1 = conv_s2s_29_30(but_11_acc_14_nl) + conv_s2s_28_30({but_5_slc_but_5_acc_13_psp_23_40_itm_1
      , but_5_conc_10_ncse_21_1_sva_1 , but_5_conc_10_ncse_0_sva_1 , 5'b00000});
  assign but_11_acc_6_psp_sva_1 = nl_but_11_acc_6_psp_sva_1[29:0];
  assign nl_but_11_acc_3_psp_sva_1 = conv_s2s_28_30({but_5_slc_but_5_acc_14_psp_23_40_itm_1
      , but_5_conc_11_ncse_21_1_sva_1 , but_5_conc_11_ncse_0_sva_1 , 5'b00000}) +
      conv_s2s_28_30(but_11_mul_psp_sva_1) + conv_s2s_28_30(but_11_mul_1_psp_sva_1);
  assign but_11_acc_3_psp_sva_1 = nl_but_11_acc_3_psp_sva_1[29:0];
  assign but_11_acc_12_nl = $signed(but_11_mul_psp_sva_1) - $signed(but_11_mul_1_psp_sva_1);
  assign nl_but_11_acc_psp_sva_1 = conv_s2s_29_30(but_11_acc_12_nl) + conv_s2s_28_30({but_5_slc_but_5_acc_13_psp_23_40_itm_1
      , but_5_conc_10_ncse_21_1_sva_1 , but_5_conc_10_ncse_0_sva_1 , 5'b00000});
  assign but_11_acc_psp_sva_1 = nl_but_11_acc_psp_sva_1[29:0];
  assign nl_but_9_acc_15_nl = conv_s2s_28_29(~ but_9_mul_2_psp_sva_1) + conv_s2s_28_29(~
      but_9_mul_3_psp_sva_1) + 29'b00000000000000000000000000001;
  assign but_9_acc_15_nl = nl_but_9_acc_15_nl[28:0];
  assign nl_but_9_acc_9_psp_sva_1 = conv_s2s_29_30(but_9_acc_15_nl) + conv_s2s_28_30({but_5_slc_but_5_acc_12_psp_23_40_itm_1
      , but_5_conc_9_ncse_21_1_sva_1 , but_5_conc_9_ncse_0_sva_1 , 5'b00000}) + 30'b000000000000000000000000000001;
  assign but_9_acc_9_psp_sva_1 = nl_but_9_acc_9_psp_sva_1[29:0];
  assign but_9_acc_14_nl = $signed(but_9_mul_1_psp_sva_1) - $signed(but_9_mul_psp_sva_1);
  assign nl_but_9_acc_6_psp_sva_1 = conv_s2s_29_30(but_9_acc_14_nl) + conv_s2s_28_30({but_5_slc_but_5_acc_psp_23_40_itm_1
      , but_5_conc_8_ncse_21_1_sva_1 , but_5_conc_8_ncse_0_sva_1 , 5'b00000});
  assign but_9_acc_6_psp_sva_1 = nl_but_9_acc_6_psp_sva_1[29:0];
  assign nl_but_9_acc_3_psp_sva_1 = conv_s2s_28_30({but_5_slc_but_5_acc_12_psp_23_40_itm_1
      , but_5_conc_9_ncse_21_1_sva_1 , but_5_conc_9_ncse_0_sva_1 , 5'b00000}) + conv_s2s_28_30(but_9_mul_2_psp_sva_1)
      + conv_s2s_28_30(but_9_mul_3_psp_sva_1);
  assign but_9_acc_3_psp_sva_1 = nl_but_9_acc_3_psp_sva_1[29:0];
  assign but_9_acc_12_nl = $signed(but_9_mul_psp_sva_1) - $signed(but_9_mul_1_psp_sva_1);
  assign nl_but_9_acc_psp_sva_1 = conv_s2s_29_30(but_9_acc_12_nl) + conv_s2s_28_30({but_5_slc_but_5_acc_psp_23_40_itm_1
      , but_5_conc_8_ncse_21_1_sva_1 , but_5_conc_8_ncse_0_sva_1 , 5'b00000});
  assign but_9_acc_psp_sva_1 = nl_but_9_acc_psp_sva_1[29:0];
  assign but_8_nor_ovfl_1_sva_1 = ~((z_out[23:22]!=2'b01));
  assign but_8_and_unfl_1_sva_1 = (z_out[23:22]==2'b10);
  assign nl_but_10_acc_14_psp_sva_1 = conv_s2s_23_24({but_4_slc_but_4_acc_14_psp_23_2_itm_1
      , but_4_conc_11_ncse_21_1_sva_1 , but_4_conc_11_ncse_0_sva_1}) - but_10_mul_2_psp_sva_1;
  assign but_10_acc_14_psp_sva_1 = nl_but_10_acc_14_psp_sva_1[23:0];
  assign but_10_nor_ovfl_3_sva_1 = ~((but_10_acc_14_psp_sva_1[23:22]!=2'b01));
  assign but_10_and_unfl_3_sva_1 = (but_10_acc_14_psp_sva_1[23:22]==2'b10);
  assign nl_but_10_acc_12_psp_sva_1 = conv_s2s_23_24({but_4_slc_but_4_acc_14_psp_23_2_itm_1
      , but_4_conc_11_ncse_21_1_sva_1 , but_4_conc_11_ncse_0_sva_1}) + but_10_mul_2_psp_sva_1;
  assign but_10_acc_12_psp_sva_1 = nl_but_10_acc_12_psp_sva_1[23:0];
  assign but_10_nor_ovfl_1_sva_1 = ~((but_10_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_10_and_unfl_1_sva_1 = (but_10_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_8_nor_ovfl_3_sva_1 = ~((z_out_1[23:22]!=2'b01));
  assign but_8_and_unfl_3_sva_1 = (z_out_1[23:22]==2'b10);
  assign but_8_nor_ovfl_sva_1 = ~((z_out_2[23:22]!=2'b01));
  assign but_8_and_unfl_sva_1 = (z_out_2[23:22]==2'b10);
  assign nl_but_10_acc_13_psp_sva_1 = conv_s2s_23_24({but_4_slc_but_4_acc_13_psp_23_2_itm_1
      , but_4_conc_10_ncse_21_1_sva_1 , but_4_conc_10_ncse_0_sva_1}) + but_10_mul_1_psp_sva_1;
  assign but_10_acc_13_psp_sva_1 = nl_but_10_acc_13_psp_sva_1[23:0];
  assign but_10_nor_ovfl_2_sva_1 = ~((but_10_acc_13_psp_sva_1[23:22]!=2'b01));
  assign but_10_and_unfl_2_sva_1 = (but_10_acc_13_psp_sva_1[23:22]==2'b10);
  assign nl_but_10_acc_psp_sva_1 = conv_s2s_23_24({but_4_slc_but_4_acc_13_psp_23_2_itm_1
      , but_4_conc_10_ncse_21_1_sva_1 , but_4_conc_10_ncse_0_sva_1}) - but_10_mul_1_psp_sva_1;
  assign but_10_acc_psp_sva_1 = nl_but_10_acc_psp_sva_1[23:0];
  assign but_10_nor_ovfl_sva_1 = ~((but_10_acc_psp_sva_1[23:22]!=2'b01));
  assign but_10_and_unfl_sva_1 = (but_10_acc_psp_sva_1[23:22]==2'b10);
  assign but_8_nor_ovfl_2_sva_1 = ~((z_out_3[23:22]!=2'b01));
  assign but_8_and_unfl_2_sva_1 = (z_out_3[23:22]==2'b10);
  assign nl_but_5_acc_14_psp_sva_1 = conv_s2s_23_24({but_slc_but_acc_14_psp_23_2_itm_1
      , but_conc_11_ncse_21_1_sva_1 , but_conc_11_ncse_0_sva_1}) - but_5_mul_2_psp_sva_1;
  assign but_5_acc_14_psp_sva_1 = nl_but_5_acc_14_psp_sva_1[23:0];
  assign nl_but_5_acc_13_psp_sva_1 = conv_s2s_23_24({but_slc_but_acc_13_psp_23_2_itm_1
      , but_conc_10_ncse_21_1_sva_1 , but_conc_10_ncse_0_sva_1}) + but_5_mul_1_psp_sva_1;
  assign but_5_acc_13_psp_sva_1 = nl_but_5_acc_13_psp_sva_1[23:0];
  assign nl_but_7_acc_14_psp_sva_1 = conv_s2s_23_24({but_2_slc_but_2_acc_14_psp_23_2_itm_1
      , but_2_conc_11_ncse_21_1_sva_1 , but_2_conc_11_ncse_0_sva_1}) - but_7_mul_2_psp_sva_1;
  assign but_7_acc_14_psp_sva_1 = nl_but_7_acc_14_psp_sva_1[23:0];
  assign but_7_nor_ovfl_3_sva_1 = ~((but_7_acc_14_psp_sva_1[23:22]!=2'b01));
  assign but_7_and_unfl_3_sva_1 = (but_7_acc_14_psp_sva_1[23:22]==2'b10);
  assign nl_but_7_acc_13_psp_sva_1 = conv_s2s_23_24({but_2_slc_but_2_acc_13_psp_23_2_itm_1
      , but_2_conc_10_ncse_21_1_sva_1 , but_2_conc_10_ncse_0_sva_1}) + but_7_mul_1_psp_sva_1;
  assign but_7_acc_13_psp_sva_1 = nl_but_7_acc_13_psp_sva_1[23:0];
  assign but_7_nor_ovfl_2_sva_1 = ~((but_7_acc_13_psp_sva_1[23:22]!=2'b01));
  assign but_7_and_unfl_2_sva_1 = (but_7_acc_13_psp_sva_1[23:22]==2'b10);
  assign nl_but_10_mul_2_psp_sva_1 = conv_s2s_23_24({(~ but_6_slc_but_6_acc_13_psp_23_2_itm_1)
      , but_10_but_6_or_2_itm_1 , but_10_but_6_or_3_itm_1}) + 24'b000000000000000000000001;
  assign but_10_mul_2_psp_sva_1 = nl_but_10_mul_2_psp_sva_1[23:0];
  assign nl_but_10_mul_1_psp_sva_1 = conv_s2s_23_24({(~ but_6_slc_but_6_acc_14_psp_23_2_itm_1)
      , but_10_but_6_or_itm_1 , but_10_but_6_or_1_itm_1}) + 24'b000000000000000000000001;
  assign but_10_mul_1_psp_sva_1 = nl_but_10_mul_1_psp_sva_1[23:0];
  assign nl_but_5_acc_12_psp_sva_1 = conv_s2s_23_24({but_slc_but_acc_14_psp_23_2_itm_1
      , but_conc_11_ncse_21_1_sva_1 , but_conc_11_ncse_0_sva_1}) + but_5_mul_2_psp_sva_1;
  assign but_5_acc_12_psp_sva_1 = nl_but_5_acc_12_psp_sva_1[23:0];
  assign nl_but_5_acc_psp_sva_1 = conv_s2s_23_24({but_slc_but_acc_13_psp_23_2_itm_1
      , but_conc_10_ncse_21_1_sva_1 , but_conc_10_ncse_0_sva_1}) - but_5_mul_1_psp_sva_1;
  assign but_5_acc_psp_sva_1 = nl_but_5_acc_psp_sva_1[23:0];
  assign nl_but_7_acc_12_psp_sva_1 = conv_s2s_23_24({but_2_slc_but_2_acc_14_psp_23_2_itm_1
      , but_2_conc_11_ncse_21_1_sva_1 , but_2_conc_11_ncse_0_sva_1}) + but_7_mul_2_psp_sva_1;
  assign but_7_acc_12_psp_sva_1 = nl_but_7_acc_12_psp_sva_1[23:0];
  assign nl_but_7_acc_psp_sva_1 = conv_s2s_23_24({but_2_slc_but_2_acc_13_psp_23_2_itm_1
      , but_2_conc_10_ncse_21_1_sva_1 , but_2_conc_10_ncse_0_sva_1}) - but_7_mul_1_psp_sva_1;
  assign but_7_acc_psp_sva_1 = nl_but_7_acc_psp_sva_1[23:0];
  assign but_7_nor_ovfl_1_sva_1 = ~((but_7_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_7_and_unfl_1_sva_1 = (but_7_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_7_nor_ovfl_sva_1 = ~((but_7_acc_psp_sva_1[23:22]!=2'b01));
  assign but_7_and_unfl_sva_1 = (but_7_acc_psp_sva_1[23:22]==2'b10);
  assign but_5_nor_ovfl_3_sva_1 = ~((but_5_acc_14_psp_sva_1[23:22]!=2'b01));
  assign but_5_and_unfl_3_sva_1 = (but_5_acc_14_psp_sva_1[23:22]==2'b10);
  assign but_5_nor_ovfl_2_sva_1 = ~((but_5_acc_13_psp_sva_1[23:22]!=2'b01));
  assign but_5_and_unfl_2_sva_1 = (but_5_acc_13_psp_sva_1[23:22]==2'b10);
  assign but_5_nor_ovfl_1_sva_1 = ~((but_5_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_5_and_unfl_1_sva_1 = (but_5_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_5_nor_ovfl_sva_1 = ~((but_5_acc_psp_sva_1[23:22]!=2'b01));
  assign but_5_and_unfl_sva_1 = (but_5_acc_psp_sva_1[23:22]==2'b10);
  assign nl_but_4_acc_14_psp_sva_1 = conv_s2u_23_24({(but_acc_12_psp_sva_1[23]) ,
      fft_stage1_imag_conc_3_21_1 , fft_stage1_imag_conc_3_0}) + conv_s2u_23_24({(~
      (but_1_acc_12_psp_sva_1[23])) , (~ but_1_conc_9_ncse_21_1_sva_1) , (~ but_1_conc_9_ncse_0_sva_1)})
      + 24'b000000000000000000000001;
  assign but_4_acc_14_psp_sva_1 = nl_but_4_acc_14_psp_sva_1[23:0];
  assign nl_but_4_acc_13_psp_sva_1 = conv_s2u_23_24({(but_acc_psp_sva_1[23]) , fft_stage1_real_conc_3_21_1
      , fft_stage1_real_conc_3_0}) + conv_s2u_23_24({(~ (but_1_acc_psp_sva_1[23]))
      , (~ but_1_conc_8_ncse_21_1_sva_1) , (~ but_1_conc_8_ncse_0_sva_1)}) + 24'b000000000000000000000001;
  assign but_4_acc_13_psp_sva_1 = nl_but_4_acc_13_psp_sva_1[23:0];
  assign nl_but_6_acc_13_psp_sva_1 = conv_s2u_23_24({(but_2_acc_psp_sva_1[23]) ,
      but_2_conc_80_21_1 , but_2_conc_80_0}) + conv_s2u_23_24({(~ (but_3_acc_psp_sva_1[23]))
      , (~ but_3_conc_8_ncse_21_1_sva_1) , (~ but_3_conc_8_ncse_0_sva_1)}) + 24'b000000000000000000000001;
  assign but_6_acc_13_psp_sva_1 = nl_but_6_acc_13_psp_sva_1[23:0];
  assign but_6_nor_ovfl_2_sva_1 = ~((but_6_acc_13_psp_sva_1[23:22]!=2'b01));
  assign but_6_and_unfl_2_sva_1 = (but_6_acc_13_psp_sva_1[23:22]==2'b10);
  assign nl_but_6_acc_14_psp_sva_1 = conv_s2u_23_24({(but_2_acc_12_psp_sva_1[23])
      , but_2_conc_78_21_1 , but_2_conc_78_0}) + conv_s2u_23_24({(~ (but_3_acc_12_psp_sva_1[23]))
      , (~ but_3_conc_9_ncse_21_1_sva_1) , (~ but_3_conc_9_ncse_0_sva_1)}) + 24'b000000000000000000000001;
  assign but_6_acc_14_psp_sva_1 = nl_but_6_acc_14_psp_sva_1[23:0];
  assign but_6_nor_ovfl_3_sva_1 = ~((but_6_acc_14_psp_sva_1[23:22]!=2'b01));
  assign but_6_and_unfl_3_sva_1 = (but_6_acc_14_psp_sva_1[23:22]==2'b10);
  assign nl_but_6_acc_12_psp_sva_1 = conv_s2u_23_24({(but_2_acc_12_psp_sva_1[23])
      , but_2_conc_78_21_1 , but_2_conc_78_0}) + conv_s2u_23_24({(but_3_acc_12_psp_sva_1[23])
      , but_3_conc_9_ncse_21_1_sva_1 , but_3_conc_9_ncse_0_sva_1});
  assign but_6_acc_12_psp_sva_1 = nl_but_6_acc_12_psp_sva_1[23:0];
  assign nl_but_4_acc_12_psp_sva_1 = conv_s2u_23_24({(but_acc_12_psp_sva_1[23]) ,
      fft_stage1_imag_conc_3_21_1 , fft_stage1_imag_conc_3_0}) + conv_s2u_23_24({(but_1_acc_12_psp_sva_1[23])
      , but_1_conc_9_ncse_21_1_sva_1 , but_1_conc_9_ncse_0_sva_1});
  assign but_4_acc_12_psp_sva_1 = nl_but_4_acc_12_psp_sva_1[23:0];
  assign nl_but_6_acc_psp_sva_1 = conv_s2u_23_24({(but_2_acc_psp_sva_1[23]) , but_2_conc_80_21_1
      , but_2_conc_80_0}) + conv_s2u_23_24({(but_3_acc_psp_sva_1[23]) , but_3_conc_8_ncse_21_1_sva_1
      , but_3_conc_8_ncse_0_sva_1});
  assign but_6_acc_psp_sva_1 = nl_but_6_acc_psp_sva_1[23:0];
  assign nl_but_4_acc_psp_sva_1 = conv_s2u_23_24({(but_acc_psp_sva_1[23]) , fft_stage1_real_conc_3_21_1
      , fft_stage1_real_conc_3_0}) + conv_s2u_23_24({(but_1_acc_psp_sva_1[23]) ,
      but_1_conc_8_ncse_21_1_sva_1 , but_1_conc_8_ncse_0_sva_1});
  assign but_4_acc_psp_sva_1 = nl_but_4_acc_psp_sva_1[23:0];
  assign nl_but_2_acc_14_psp_sva_1 = conv_s2u_23_24(cx_in_imag_1_sva_mx0) - conv_s2u_23_24(cx_in_imag_5_sva_mx0);
  assign but_2_acc_14_psp_sva_1 = nl_but_2_acc_14_psp_sva_1[23:0];
  assign nl_but_2_acc_13_psp_sva_1 = conv_s2u_23_24(cx_in_real_1_sva_mx0) - conv_s2u_23_24(cx_in_real_5_sva_mx0);
  assign but_2_acc_13_psp_sva_1 = nl_but_2_acc_13_psp_sva_1[23:0];
  assign nl_but_2_acc_12_psp_sva_1 = conv_s2u_23_24(cx_in_imag_1_sva_mx0) + conv_s2u_23_24(cx_in_imag_5_sva_mx0);
  assign but_2_acc_12_psp_sva_1 = nl_but_2_acc_12_psp_sva_1[23:0];
  assign nl_but_3_acc_12_psp_sva_1 = conv_s2u_23_24(cx_in_imag_3_sva_mx0) + conv_s2u_23_24(cx_in_imag_7_sva_mx0);
  assign but_3_acc_12_psp_sva_1 = nl_but_3_acc_12_psp_sva_1[23:0];
  assign but_3_nor_12_nl = ~(MUX_v_21_2_2((but_3_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_3_nor_ovfl_1_sva_1));
  assign but_3_conc_9_ncse_21_1_sva_1 = ~(MUX_v_21_2_2(but_3_nor_12_nl, 21'b111111111111111111111,
      but_3_and_unfl_1_sva_1));
  assign but_3_conc_9_ncse_0_sva_1 = ~((~((but_3_acc_12_psp_sva_1[0]) | but_3_nor_ovfl_1_sva_1))
      | but_3_and_unfl_1_sva_1);
  assign nl_but_2_acc_psp_sva_1 = conv_s2u_23_24(cx_in_real_1_sva_mx0) + conv_s2u_23_24(cx_in_real_5_sva_mx0);
  assign but_2_acc_psp_sva_1 = nl_but_2_acc_psp_sva_1[23:0];
  assign nl_but_3_acc_psp_sva_1 = conv_s2u_23_24(cx_in_real_3_sva_mx0) + conv_s2u_23_24(cx_in_real_7_sva_mx0);
  assign but_3_acc_psp_sva_1 = nl_but_3_acc_psp_sva_1[23:0];
  assign but_3_nor_9_nl = ~(MUX_v_21_2_2((but_3_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_3_nor_ovfl_sva_1));
  assign but_3_conc_8_ncse_21_1_sva_1 = ~(MUX_v_21_2_2(but_3_nor_9_nl, 21'b111111111111111111111,
      but_3_and_unfl_sva_1));
  assign but_3_conc_8_ncse_0_sva_1 = ~((~((but_3_acc_psp_sva_1[0]) | but_3_nor_ovfl_sva_1))
      | but_3_and_unfl_sva_1);
  assign but_6_nor_ovfl_1_sva_1 = ~((but_6_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_6_and_unfl_1_sva_1 = (but_6_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_6_nor_ovfl_sva_1 = ~((but_6_acc_psp_sva_1[23:22]!=2'b01));
  assign but_6_and_unfl_sva_1 = (but_6_acc_psp_sva_1[23:22]==2'b10);
  assign nl_but_acc_14_psp_sva_1 = conv_s2u_23_24(cx_in_imag_0_sva_mx0) - conv_s2u_23_24(cx_in_imag_4_sva_mx0);
  assign but_acc_14_psp_sva_1 = nl_but_acc_14_psp_sva_1[23:0];
  assign nl_but_acc_13_psp_sva_1 = conv_s2u_23_24(cx_in_real_0_sva_mx0) - conv_s2u_23_24(cx_in_real_4_sva_mx0);
  assign but_acc_13_psp_sva_1 = nl_but_acc_13_psp_sva_1[23:0];
  assign but_4_nor_ovfl_3_sva_1 = ~((but_4_acc_14_psp_sva_1[23:22]!=2'b01));
  assign but_4_and_unfl_3_sva_1 = (but_4_acc_14_psp_sva_1[23:22]==2'b10);
  assign nl_but_acc_12_psp_sva_1 = conv_s2u_23_24(cx_in_imag_0_sva_mx0) + conv_s2u_23_24(cx_in_imag_4_sva_mx0);
  assign but_acc_12_psp_sva_1 = nl_but_acc_12_psp_sva_1[23:0];
  assign nl_but_1_acc_12_psp_sva_1 = conv_s2u_23_24(cx_in_imag_2_sva_mx0) + conv_s2u_23_24(cx_in_imag_6_sva_mx0);
  assign but_1_acc_12_psp_sva_1 = nl_but_1_acc_12_psp_sva_1[23:0];
  assign but_1_nor_12_nl = ~(MUX_v_21_2_2((but_1_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_1_nor_ovfl_1_sva_1));
  assign but_1_conc_9_ncse_21_1_sva_1 = ~(MUX_v_21_2_2(but_1_nor_12_nl, 21'b111111111111111111111,
      but_1_and_unfl_1_sva_1));
  assign but_1_conc_9_ncse_0_sva_1 = ~((~((but_1_acc_12_psp_sva_1[0]) | but_1_nor_ovfl_1_sva_1))
      | but_1_and_unfl_1_sva_1);
  assign but_4_nor_ovfl_2_sva_1 = ~((but_4_acc_13_psp_sva_1[23:22]!=2'b01));
  assign but_4_and_unfl_2_sva_1 = (but_4_acc_13_psp_sva_1[23:22]==2'b10);
  assign nl_but_acc_psp_sva_1 = conv_s2u_23_24(cx_in_real_0_sva_mx0) + conv_s2u_23_24(cx_in_real_4_sva_mx0);
  assign but_acc_psp_sva_1 = nl_but_acc_psp_sva_1[23:0];
  assign nl_but_1_acc_psp_sva_1 = conv_s2u_23_24(cx_in_real_2_sva_mx0) + conv_s2u_23_24(cx_in_real_6_sva_mx0);
  assign but_1_acc_psp_sva_1 = nl_but_1_acc_psp_sva_1[23:0];
  assign but_1_nor_9_nl = ~(MUX_v_21_2_2((but_1_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_1_nor_ovfl_sva_1));
  assign but_1_conc_8_ncse_21_1_sva_1 = ~(MUX_v_21_2_2(but_1_nor_9_nl, 21'b111111111111111111111,
      but_1_and_unfl_sva_1));
  assign but_1_conc_8_ncse_0_sva_1 = ~((~((but_1_acc_psp_sva_1[0]) | but_1_nor_ovfl_sva_1))
      | but_1_and_unfl_sva_1);
  assign but_4_nor_ovfl_1_sva_1 = ~((but_4_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_4_and_unfl_1_sva_1 = (but_4_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_4_nor_ovfl_sva_1 = ~((but_4_acc_psp_sva_1[23:22]!=2'b01));
  assign but_4_and_unfl_sva_1 = (but_4_acc_psp_sva_1[23:22]==2'b10);
  assign cx_in_imag_3_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_3_sva, or_dcpl_17);
  assign cx_in_imag_7_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_7_sva, or_dcpl_22);
  assign cx_in_real_3_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_3_sva, or_dcpl_17);
  assign cx_in_real_7_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_7_sva, or_dcpl_22);
  assign but_3_nor_ovfl_1_sva_1 = ~((but_3_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_3_and_unfl_1_sva_1 = (but_3_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_3_nor_ovfl_sva_1 = ~((but_3_acc_psp_sva_1[23:22]!=2'b01));
  assign but_3_and_unfl_sva_1 = (but_3_acc_psp_sva_1[23:22]==2'b10);
  assign but_2_nor_ovfl_3_sva_1 = ~((but_2_acc_14_psp_sva_1[23:22]!=2'b01));
  assign but_2_and_unfl_3_sva_1 = (but_2_acc_14_psp_sva_1[23:22]==2'b10);
  assign cx_in_imag_1_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_1_sva, or_dcpl_28);
  assign cx_in_imag_5_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_5_sva, or_dcpl_32);
  assign but_2_nor_ovfl_2_sva_1 = ~((but_2_acc_13_psp_sva_1[23:22]!=2'b01));
  assign but_2_and_unfl_2_sva_1 = (but_2_acc_13_psp_sva_1[23:22]==2'b10);
  assign cx_in_real_1_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_1_sva, or_dcpl_28);
  assign cx_in_real_5_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_5_sva, or_dcpl_32);
  assign but_2_nor_ovfl_1_sva_1 = ~((but_2_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_2_and_unfl_1_sva_1 = (but_2_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_2_nor_ovfl_sva_1 = ~((but_2_acc_psp_sva_1[23:22]!=2'b01));
  assign but_2_and_unfl_sva_1 = (but_2_acc_psp_sva_1[23:22]==2'b10);
  assign cx_in_imag_2_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_2_sva, or_dcpl_37);
  assign cx_in_imag_6_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_6_sva, or_dcpl_41);
  assign cx_in_real_2_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_2_sva, or_dcpl_37);
  assign cx_in_real_6_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_6_sva, or_dcpl_41);
  assign but_1_nor_ovfl_1_sva_1 = ~((but_1_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_1_and_unfl_1_sva_1 = (but_1_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_1_nor_ovfl_sva_1 = ~((but_1_acc_psp_sva_1[23:22]!=2'b01));
  assign but_1_and_unfl_sva_1 = (but_1_acc_psp_sva_1[23:22]==2'b10);
  assign but_nor_ovfl_3_sva_1 = ~((but_acc_14_psp_sva_1[23:22]!=2'b01));
  assign but_and_unfl_3_sva_1 = (but_acc_14_psp_sva_1[23:22]==2'b10);
  assign cx_in_imag_0_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_0_sva, or_dcpl_46);
  assign cx_in_imag_4_sva_mx0 = MUX_v_23_2_2(in_img, cx_in_imag_4_sva, or_dcpl_50);
  assign but_nor_ovfl_2_sva_1 = ~((but_acc_13_psp_sva_1[23:22]!=2'b01));
  assign but_and_unfl_2_sva_1 = (but_acc_13_psp_sva_1[23:22]==2'b10);
  assign cx_in_real_0_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_0_sva, or_dcpl_46);
  assign cx_in_real_4_sva_mx0 = MUX_v_23_2_2(in_real, cx_in_real_4_sva, or_dcpl_50);
  assign but_nor_ovfl_1_sva_1 = ~((but_acc_12_psp_sva_1[23:22]!=2'b01));
  assign but_and_unfl_1_sva_1 = (but_acc_12_psp_sva_1[23:22]==2'b10);
  assign but_nor_ovfl_sva_1 = ~((but_acc_psp_sva_1[23:22]!=2'b01));
  assign but_and_unfl_sva_1 = (but_acc_psp_sva_1[23:22]==2'b10);
  assign but_7_nor_12_nl = ~(MUX_v_21_2_2((but_7_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_7_nor_ovfl_1_sva_1));
  assign but_7_conc_76_21_1 = ~(MUX_v_21_2_2(but_7_nor_12_nl, 21'b111111111111111111111,
      but_7_and_unfl_1_sva_1));
  assign but_7_conc_76_0 = ~((~((but_7_acc_12_psp_sva_1[0]) | but_7_nor_ovfl_1_sva_1))
      | but_7_and_unfl_1_sva_1);
  assign but_7_nor_9_nl = ~(MUX_v_21_2_2((but_7_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_7_nor_ovfl_sva_1));
  assign but_7_conc_78_21_1 = ~(MUX_v_21_2_2(but_7_nor_9_nl, 21'b111111111111111111111,
      but_7_and_unfl_sva_1));
  assign but_7_conc_78_0 = ~((~((but_7_acc_psp_sva_1[0]) | but_7_nor_ovfl_sva_1))
      | but_7_and_unfl_sva_1);
  assign but_2_nor_12_nl = ~(MUX_v_21_2_2((but_2_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_2_nor_ovfl_1_sva_1));
  assign but_2_conc_78_21_1 = ~(MUX_v_21_2_2(but_2_nor_12_nl, 21'b111111111111111111111,
      but_2_and_unfl_1_sva_1));
  assign but_2_conc_78_0 = ~((~((but_2_acc_12_psp_sva_1[0]) | but_2_nor_ovfl_1_sva_1))
      | but_2_and_unfl_1_sva_1);
  assign but_2_nor_9_nl = ~(MUX_v_21_2_2((but_2_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_2_nor_ovfl_sva_1));
  assign but_2_conc_80_21_1 = ~(MUX_v_21_2_2(but_2_nor_9_nl, 21'b111111111111111111111,
      but_2_and_unfl_sva_1));
  assign but_2_conc_80_0 = ~((~((but_2_acc_psp_sva_1[0]) | but_2_nor_ovfl_sva_1))
      | but_2_and_unfl_sva_1);
  assign but_nor_12_nl = ~(MUX_v_21_2_2((but_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_nor_ovfl_1_sva_1));
  assign fft_stage1_imag_conc_3_21_1 = ~(MUX_v_21_2_2(but_nor_12_nl, 21'b111111111111111111111,
      but_and_unfl_1_sva_1));
  assign fft_stage1_imag_conc_3_0 = ~((~((but_acc_12_psp_sva_1[0]) | but_nor_ovfl_1_sva_1))
      | but_and_unfl_1_sva_1);
  assign but_nor_9_nl = ~(MUX_v_21_2_2((but_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_nor_ovfl_sva_1));
  assign fft_stage1_real_conc_3_21_1 = ~(MUX_v_21_2_2(but_nor_9_nl, 21'b111111111111111111111,
      but_and_unfl_sva_1));
  assign fft_stage1_real_conc_3_0 = ~((~((but_acc_psp_sva_1[0]) | but_nor_ovfl_sva_1))
      | but_and_unfl_sva_1);
  assign and_dcpl_5 = while_stage_0_3 & (~ while_asn_itm_2);
  assign or_dcpl_7 = (~ while_stage_0_3) | while_asn_itm_2 | (~ while_if_land_1_lpi_1_dfm_st_1);
  assign and_dcpl_14 = i_sva_3 & while_if_aelse_nor_itm_1;
  assign or_dcpl_10 = processing_sva | (~ while_stage_0_2);
  assign or_dcpl_12 = ~(while_stage_0_3 & while_asn_itm_2);
  assign or_dcpl_13 = ~((i_sva_2_0[1:0]==2'b11));
  assign or_dcpl_16 = and_dcpl_14 | (~ data_valid_source) | processing_sva;
  assign or_dcpl_17 = or_dcpl_16 | or_dcpl_13 | (i_sva_2_0[2]);
  assign or_dcpl_18 = (i_sva_2_0[2]) | (~ while_stage_0_2);
  assign or_dcpl_20 = or_dcpl_16 | or_dcpl_13 | or_dcpl_18;
  assign or_dcpl_22 = or_dcpl_16 | or_dcpl_13 | (~ (i_sva_2_0[2]));
  assign or_dcpl_23 = ~((i_sva_2_0[2]) & while_stage_0_2);
  assign or_dcpl_25 = or_dcpl_16 | or_dcpl_13 | or_dcpl_23;
  assign or_dcpl_26 = (i_sva_2_0[1:0]!=2'b01);
  assign or_dcpl_28 = or_dcpl_16 | or_dcpl_26 | (i_sva_2_0[2]);
  assign or_dcpl_30 = or_dcpl_16 | or_dcpl_26 | or_dcpl_18;
  assign or_dcpl_32 = or_dcpl_16 | or_dcpl_26 | (~ (i_sva_2_0[2]));
  assign or_dcpl_34 = or_dcpl_16 | or_dcpl_26 | or_dcpl_23;
  assign or_dcpl_35 = (i_sva_2_0[1:0]!=2'b10);
  assign or_dcpl_37 = or_dcpl_16 | or_dcpl_35 | (i_sva_2_0[2]);
  assign or_dcpl_39 = or_dcpl_16 | or_dcpl_35 | or_dcpl_18;
  assign or_dcpl_41 = or_dcpl_16 | or_dcpl_35 | (~ (i_sva_2_0[2]));
  assign or_dcpl_43 = or_dcpl_16 | or_dcpl_35 | or_dcpl_23;
  assign or_dcpl_44 = (i_sva_2_0[1:0]!=2'b00);
  assign or_dcpl_46 = or_dcpl_16 | or_dcpl_44 | (i_sva_2_0[2]);
  assign or_dcpl_48 = or_dcpl_16 | or_dcpl_44 | or_dcpl_18;
  assign or_dcpl_50 = or_dcpl_16 | or_dcpl_44 | (~ (i_sva_2_0[2]));
  assign or_dcpl_52 = or_dcpl_16 | or_dcpl_44 | or_dcpl_23;
  assign data_valid_sink_mx0c1 = ((while_if_while_if_if_and_itm_2 & (~ while_if_land_1_lpi_1_dfm_st_1))
      | while_asn_itm_2) & while_stage_0_3;
  assign data_req_source_mx0c0 = and_dcpl_5 & while_if_land_2_lpi_1_dfm_st_1;
  assign xor_dcpl = while_stage_0_2 ^ processing_sva;
  assign but_8_or_cse = ~(processing_sva & while_stage_0_2);
  always @(posedge clk) begin
    if ( rst ) begin
      data_valid_sink <= 1'b0;
    end
    else if ( (and_dcpl_5 & while_if_land_1_lpi_1_dfm_st_1) | data_valid_sink_mx0c1
        ) begin
      data_valid_sink <= ~ data_valid_sink_mx0c1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      while_if_if_2_mux_3_itm_1 <= 1'b0;
    end
    else if ( ~ or_dcpl_7 ) begin
      while_if_if_2_mux_3_itm_1 <= while_if_if_2_mux_3_itm_1_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      while_if_if_2_mux_4_itm_1 <= 21'b000000000000000000000;
    end
    else if ( ~ or_dcpl_7 ) begin
      while_if_if_2_mux_4_itm_1 <= while_if_if_2_mux_4_itm_1_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      while_if_if_2_mux_5_itm_1 <= 1'b0;
    end
    else if ( ~ or_dcpl_7 ) begin
      while_if_if_2_mux_5_itm_1 <= while_if_if_2_mux_5_itm_1_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      while_if_if_2_conc_itm_1_22 <= 1'b0;
    end
    else if ( ~ or_dcpl_7 ) begin
      while_if_if_2_conc_itm_1_22 <= while_if_if_2_conc_itm_1_22_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      while_if_if_2_conc_itm_1_21_1 <= 21'b000000000000000000000;
    end
    else if ( ~ or_dcpl_7 ) begin
      while_if_if_2_conc_itm_1_21_1 <= while_if_if_2_conc_itm_1_21_1_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      while_if_if_2_conc_itm_1_0 <= 1'b0;
    end
    else if ( ~ or_dcpl_7 ) begin
      while_if_if_2_conc_itm_1_0 <= while_if_if_2_conc_itm_1_0_1;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      data_req_source <= 1'b1;
    end
    else if ( data_req_source_mx0c0 | (while_stage_0_3 & while_asn_itm_2) ) begin
      data_req_source <= ~ data_req_source_mx0c0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      while_if_land_2_lpi_1_dfm_st_1 <= 1'b0;
      while_if_land_1_lpi_1_dfm_st_1 <= 1'b0;
      while_if_while_if_if_and_itm_2 <= 1'b0;
      while_asn_itm_2 <= 1'b0;
      while_if_if_nor_cse_sva_1 <= 1'b0;
      while_if_aelse_nor_itm_1 <= 1'b0;
      while_stage_0_2 <= 1'b0;
      while_stage_0_3 <= 1'b0;
      while_if_while_if_if_and_itm_1 <= 1'b0;
    end
    else begin
      while_if_land_2_lpi_1_dfm_st_1 <= while_if_land_2_lpi_1_dfm_1;
      while_if_land_1_lpi_1_dfm_st_1 <= while_if_aif_1_while_if_aelse_1_nand_cse
          & data_req_sink;
      while_if_while_if_if_and_itm_2 <= while_if_while_if_if_and_itm_1;
      while_asn_itm_2 <= processing_sva;
      while_if_if_nor_cse_sva_1 <= while_if_if_nor_cse_sva_1_1;
      while_if_aelse_nor_itm_1 <= ~((i_sva_31_4_mx0!=28'b0000000000000000000000000000)
          | (i_sva_2_0_mx0!=3'b000));
      while_stage_0_2 <= 1'b1;
      while_stage_0_3 <= while_stage_0_2;
      while_if_while_if_if_and_itm_1 <= while_if_mux_2_nl & while_if_if_nor_cse_sva_1_1;
    end
  end
  always @(posedge clk) begin
    while_if_if_2_mux_3_itm_1_1 <= MUX_s_1_8_2(but_8_acc_12_psp_lpi_1_dfm_23, but_9_acc_5_psp_1_lpi_1_dfm_24_mx0,
        but_10_acc_12_psp_lpi_1_dfm_23, but_11_acc_5_psp_1_lpi_1_dfm_24_mx0, but_8_acc_14_psp_lpi_1_dfm_23,
        but_9_acc_11_psp_1_lpi_1_dfm_24_mx0, but_10_acc_14_psp_lpi_1_dfm_23, but_11_acc_11_psp_1_lpi_1_dfm_24_mx0,
        j_sva_2_0);
    while_if_if_2_mux_4_itm_1_1 <= MUX_v_21_8_2(cx_out_imag_0_21_1_sva_dfm, cx_out_imag_1_21_1_sva_dfm_mx0,
        cx_out_imag_2_21_1_sva_dfm, cx_out_imag_3_21_1_sva_dfm_mx0, cx_out_imag_4_21_1_sva_dfm,
        cx_out_imag_5_21_1_sva_dfm_mx0, cx_out_imag_6_21_1_sva_dfm, cx_out_imag_7_21_1_sva_dfm_mx0,
        j_sva_2_0);
    while_if_if_2_mux_5_itm_1_1 <= MUX_s_1_8_2(cx_out_imag_0_0_sva_dfm, cx_out_imag_1_0_sva_dfm_mx0,
        cx_out_imag_2_0_sva_dfm, cx_out_imag_3_0_sva_dfm_mx0, cx_out_imag_4_0_sva_dfm,
        cx_out_imag_5_0_sva_dfm_mx0, cx_out_imag_6_0_sva_dfm, cx_out_imag_7_0_sva_dfm_mx0,
        j_sva_2_0);
    while_if_if_2_conc_itm_1_22_1 <= MUX_s_1_8_2(but_8_acc_psp_lpi_1_dfm_23, but_9_acc_2_psp_1_lpi_1_dfm_24_mx0,
        but_10_acc_psp_lpi_1_dfm_23, but_11_acc_2_psp_1_lpi_1_dfm_24_mx0, but_8_acc_13_psp_lpi_1_dfm_23,
        but_9_acc_8_psp_1_lpi_1_dfm_24_mx0, but_10_acc_13_psp_lpi_1_dfm_23, but_11_acc_8_psp_1_lpi_1_dfm_24_mx0,
        j_sva_2_0);
    while_if_if_2_conc_itm_1_21_1_1 <= MUX_v_21_8_2(cx_out_real_0_21_1_sva_dfm, cx_out_real_1_21_1_sva_dfm_mx0,
        cx_out_real_2_21_1_sva_dfm, cx_out_real_3_21_1_sva_dfm_mx0, cx_out_real_4_21_1_sva_dfm,
        cx_out_real_5_21_1_sva_dfm_mx0, cx_out_real_6_21_1_sva_dfm, cx_out_real_7_21_1_sva_dfm_mx0,
        j_sva_2_0);
    while_if_if_2_conc_itm_1_0_1 <= MUX_s_1_8_2(cx_out_real_0_0_sva_dfm, cx_out_real_1_0_sva_dfm_mx0,
        cx_out_real_2_0_sva_dfm, cx_out_real_3_0_sva_dfm_mx0, cx_out_real_4_0_sva_dfm,
        cx_out_real_5_0_sva_dfm_mx0, cx_out_real_6_0_sva_dfm, cx_out_real_7_0_sva_dfm_mx0,
        j_sva_2_0);
    cx_out_imag_7_0_sva_dfm <= cx_out_imag_7_0_sva_dfm_mx0;
    cx_out_imag_7_21_1_sva_dfm <= cx_out_imag_7_21_1_sva_dfm_mx0;
    cx_out_imag_5_0_sva_dfm <= cx_out_imag_5_0_sva_dfm_mx0;
    cx_out_imag_5_21_1_sva_dfm <= cx_out_imag_5_21_1_sva_dfm_mx0;
    cx_out_imag_3_0_sva_dfm <= cx_out_imag_3_0_sva_dfm_mx0;
    cx_out_imag_3_21_1_sva_dfm <= cx_out_imag_3_21_1_sva_dfm_mx0;
    cx_out_imag_1_0_sva_dfm <= cx_out_imag_1_0_sva_dfm_mx0;
    cx_out_imag_1_21_1_sva_dfm <= cx_out_imag_1_21_1_sva_dfm_mx0;
    cx_out_real_7_0_sva_dfm <= cx_out_real_7_0_sva_dfm_mx0;
    cx_out_real_7_21_1_sva_dfm <= cx_out_real_7_21_1_sva_dfm_mx0;
    cx_out_real_5_0_sva_dfm <= cx_out_real_5_0_sva_dfm_mx0;
    cx_out_real_5_21_1_sva_dfm <= cx_out_real_5_21_1_sva_dfm_mx0;
    cx_out_real_3_0_sva_dfm <= cx_out_real_3_0_sva_dfm_mx0;
    cx_out_real_3_21_1_sva_dfm <= cx_out_real_3_21_1_sva_dfm_mx0;
    cx_out_real_1_0_sva_dfm <= cx_out_real_1_0_sva_dfm_mx0;
    cx_out_real_1_21_1_sva_dfm <= cx_out_real_1_21_1_sva_dfm_mx0;
    but_11_acc_11_psp_1_lpi_1_dfm_24 <= but_11_acc_11_psp_1_lpi_1_dfm_24_mx0;
    but_11_acc_8_psp_1_lpi_1_dfm_24 <= but_11_acc_8_psp_1_lpi_1_dfm_24_mx0;
    but_11_acc_5_psp_1_lpi_1_dfm_24 <= but_11_acc_5_psp_1_lpi_1_dfm_24_mx0;
    but_11_acc_2_psp_1_lpi_1_dfm_24 <= but_11_acc_2_psp_1_lpi_1_dfm_24_mx0;
    but_9_acc_11_psp_1_lpi_1_dfm_24 <= but_9_acc_11_psp_1_lpi_1_dfm_24_mx0;
    but_9_acc_8_psp_1_lpi_1_dfm_24 <= but_9_acc_8_psp_1_lpi_1_dfm_24_mx0;
    but_9_acc_5_psp_1_lpi_1_dfm_24 <= but_9_acc_5_psp_1_lpi_1_dfm_24_mx0;
    but_9_acc_2_psp_1_lpi_1_dfm_24 <= but_9_acc_2_psp_1_lpi_1_dfm_24_mx0;
    but_11_mul_psp_sva_1 <= nl_but_11_mul_psp_sva_1[27:0];
    but_11_mul_1_psp_sva_1 <= nl_but_11_mul_1_psp_sva_1[27:0];
    but_5_slc_but_5_acc_14_psp_23_40_itm_1 <= but_5_acc_14_psp_sva_1[23];
    but_5_conc_11_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_5_nor_18_nl, 21'b111111111111111111111,
        but_5_and_unfl_3_sva_1));
    but_5_conc_11_ncse_0_sva_1 <= ~((~((but_5_acc_14_psp_sva_1[0]) | but_5_nor_ovfl_3_sva_1))
        | but_5_and_unfl_3_sva_1);
    but_5_slc_but_5_acc_13_psp_23_40_itm_1 <= but_5_acc_13_psp_sva_1[23];
    but_5_conc_10_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_5_nor_15_nl, 21'b111111111111111111111,
        but_5_and_unfl_2_sva_1));
    but_5_conc_10_ncse_0_sva_1 <= ~((~((but_5_acc_13_psp_sva_1[0]) | but_5_nor_ovfl_2_sva_1))
        | but_5_and_unfl_2_sva_1);
    but_9_mul_2_psp_sva_1 <= nl_but_9_mul_2_psp_sva_1[27:0];
    but_9_mul_3_psp_sva_1 <= nl_but_9_mul_3_psp_sva_1[27:0];
    but_5_slc_but_5_acc_12_psp_23_40_itm_1 <= but_5_acc_12_psp_sva_1[23];
    but_5_conc_9_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_5_nor_12_nl, 21'b111111111111111111111,
        but_5_and_unfl_1_sva_1));
    but_5_conc_9_ncse_0_sva_1 <= ~((~((but_5_acc_12_psp_sva_1[0]) | but_5_nor_ovfl_1_sva_1))
        | but_5_and_unfl_1_sva_1);
    but_9_mul_psp_sva_1 <= nl_but_9_mul_psp_sva_1[27:0];
    but_9_mul_1_psp_sva_1 <= nl_but_9_mul_1_psp_sva_1[27:0];
    but_5_slc_but_5_acc_psp_23_40_itm_1 <= but_5_acc_psp_sva_1[23];
    but_5_conc_8_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_5_nor_9_nl, 21'b111111111111111111111,
        but_5_and_unfl_sva_1));
    but_5_conc_8_ncse_0_sva_1 <= ~((~((but_5_acc_psp_sva_1[0]) | but_5_nor_ovfl_sva_1))
        | but_5_and_unfl_sva_1);
    but_4_slc_but_4_acc_14_psp_23_2_itm_1 <= but_4_acc_14_psp_sva_1[23];
    but_4_conc_11_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_4_nor_18_nl, 21'b111111111111111111111,
        but_4_and_unfl_3_sva_1));
    but_4_conc_11_ncse_0_sva_1 <= ~((~((but_4_acc_14_psp_sva_1[0]) | but_4_nor_ovfl_3_sva_1))
        | but_4_and_unfl_3_sva_1);
    but_4_slc_but_4_acc_13_psp_23_2_itm_1 <= but_4_acc_13_psp_sva_1[23];
    but_4_conc_10_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_4_nor_15_nl, 21'b111111111111111111111,
        but_4_and_unfl_2_sva_1));
    but_4_conc_10_ncse_0_sva_1 <= ~((~((but_4_acc_13_psp_sva_1[0]) | but_4_nor_ovfl_2_sva_1))
        | but_4_and_unfl_2_sva_1);
    but_6_slc_but_6_acc_13_psp_23_2_itm_1 <= but_6_acc_13_psp_sva_1[23];
    but_10_but_6_or_2_itm_1 <= MUX_v_21_2_2(but_6_nor_15_nl, 21'b111111111111111111111,
        but_6_and_unfl_2_sva_1);
    but_10_but_6_or_3_itm_1 <= (~((but_6_acc_13_psp_sva_1[0]) | but_6_nor_ovfl_2_sva_1))
        | but_6_and_unfl_2_sva_1;
    but_6_slc_but_6_acc_14_psp_23_2_itm_1 <= but_6_acc_14_psp_sva_1[23];
    but_10_but_6_or_itm_1 <= MUX_v_21_2_2(but_6_nor_18_nl, 21'b111111111111111111111,
        but_6_and_unfl_3_sva_1);
    but_10_but_6_or_1_itm_1 <= (~((but_6_acc_14_psp_sva_1[0]) | but_6_nor_ovfl_3_sva_1))
        | but_6_and_unfl_3_sva_1;
    but_4_slc_but_4_acc_12_psp_23_2_itm_1 <= but_4_acc_12_psp_sva_1[23];
    fft_stage2_imag_0_21_1_sva_1 <= ~(MUX_v_21_2_2(but_4_nor_12_nl, 21'b111111111111111111111,
        but_4_and_unfl_1_sva_1));
    fft_stage2_imag_0_0_sva_1 <= ~((~((but_4_acc_12_psp_sva_1[0]) | but_4_nor_ovfl_1_sva_1))
        | but_4_and_unfl_1_sva_1);
    but_6_slc_but_6_acc_12_psp_23_2_itm_1 <= but_6_acc_12_psp_sva_1[23];
    but_6_conc_9_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_6_nor_12_nl, 21'b111111111111111111111,
        but_6_and_unfl_1_sva_1));
    but_6_conc_9_ncse_0_sva_1 <= ~((~((but_6_acc_12_psp_sva_1[0]) | but_6_nor_ovfl_1_sva_1))
        | but_6_and_unfl_1_sva_1);
    but_4_slc_but_4_acc_psp_23_2_itm_1 <= but_4_acc_psp_sva_1[23];
    fft_stage2_real_0_21_1_sva_1 <= ~(MUX_v_21_2_2(but_4_nor_9_nl, 21'b111111111111111111111,
        but_4_and_unfl_sva_1));
    fft_stage2_real_0_0_sva_1 <= ~((~((but_4_acc_psp_sva_1[0]) | but_4_nor_ovfl_sva_1))
        | but_4_and_unfl_sva_1);
    but_6_slc_but_6_acc_psp_23_2_itm_1 <= but_6_acc_psp_sva_1[23];
    but_6_conc_8_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_6_nor_9_nl, 21'b111111111111111111111,
        but_6_and_unfl_sva_1));
    but_6_conc_8_ncse_0_sva_1 <= ~((~((but_6_acc_psp_sva_1[0]) | but_6_nor_ovfl_sva_1))
        | but_6_and_unfl_sva_1);
    but_7_mul_2_psp_sva_1 <= nl_but_7_mul_2_psp_sva_1[23:0];
    but_2_slc_but_2_acc_14_psp_23_2_itm_1 <= but_2_acc_14_psp_sva_1[23];
    but_2_conc_11_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_2_nor_18_nl, 21'b111111111111111111111,
        but_2_and_unfl_3_sva_1));
    but_2_conc_11_ncse_0_sva_1 <= ~((~((but_2_acc_14_psp_sva_1[0]) | but_2_nor_ovfl_3_sva_1))
        | but_2_and_unfl_3_sva_1);
    but_2_slc_but_2_acc_13_psp_23_2_itm_1 <= but_2_acc_13_psp_sva_1[23];
    but_2_conc_10_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_2_nor_15_nl, 21'b111111111111111111111,
        but_2_and_unfl_2_sva_1));
    but_2_conc_10_ncse_0_sva_1 <= ~((~((but_2_acc_13_psp_sva_1[0]) | but_2_nor_ovfl_2_sva_1))
        | but_2_and_unfl_2_sva_1);
    but_7_mul_1_psp_sva_1 <= nl_but_7_mul_1_psp_sva_1[23:0];
    but_5_mul_2_psp_sva_1 <= nl_but_5_mul_2_psp_sva_1[23:0];
    but_slc_but_acc_14_psp_23_2_itm_1 <= but_acc_14_psp_sva_1[23];
    but_conc_11_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_nor_18_nl, 21'b111111111111111111111,
        but_and_unfl_3_sva_1));
    but_conc_11_ncse_0_sva_1 <= ~((~((but_acc_14_psp_sva_1[0]) | but_nor_ovfl_3_sva_1))
        | but_and_unfl_3_sva_1);
    but_slc_but_acc_13_psp_23_2_itm_1 <= but_acc_13_psp_sva_1[23];
    but_conc_10_ncse_21_1_sva_1 <= ~(MUX_v_21_2_2(but_nor_15_nl, 21'b111111111111111111111,
        but_and_unfl_2_sva_1));
    but_conc_10_ncse_0_sva_1 <= ~((~((but_acc_13_psp_sva_1[0]) | but_nor_ovfl_2_sva_1))
        | but_and_unfl_2_sva_1);
    but_5_mul_1_psp_sva_1 <= nl_but_5_mul_1_psp_sva_1[23:0];
  end
  always @(posedge clk) begin
    if ( rst ) begin
      processing_sva <= 1'b0;
    end
    else if ( while_stage_0_2 ) begin
      processing_sva <= while_if_land_2_lpi_1_dfm_1 & (~ processing_sva);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      i_sva_31_4 <= 28'b0000000000000000000000000000;
    end
    else if ( ~ or_dcpl_10 ) begin
      i_sva_31_4 <= i_sva_dfm_mx0_31_4;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      i_sva_3 <= 1'b0;
    end
    else if ( ~ or_dcpl_10 ) begin
      i_sva_3 <= i_sva_dfm_mx0_3 & (~ while_if_land_2_lpi_1_dfm_1);
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      i_sva_2_0 <= 3'b000;
    end
    else if ( ~ or_dcpl_10 ) begin
      i_sva_2_0 <= i_sva_dfm_mx0_2_0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      j_sva_31_4 <= 28'b0000000000000000000000000000;
    end
    else if ( ~ or_dcpl_10 ) begin
      j_sva_31_4 <= j_sva_dfm_mx0_31_4;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      j_sva_3 <= 1'b1;
    end
    else if ( ~ or_dcpl_10 ) begin
      j_sva_3 <= while_if_while_if_and_1_mx0w0;
    end
  end
  always @(posedge clk) begin
    if ( rst ) begin
      j_sva_2_0 <= 3'b000;
    end
    else if ( ~ or_dcpl_10 ) begin
      j_sva_2_0 <= j_sva_dfm_mx0_2_0;
    end
  end
  always @(posedge clk) begin
    if ( processing_sva ) begin
      cx_out_imag_0_0_sva_dfm <= ~(but_8_nor_13_cse | but_8_and_unfl_1_sva_1);
      cx_out_imag_2_0_sva_dfm <= ~((~((but_10_acc_12_psp_sva_1[0]) | but_10_nor_ovfl_1_sva_1))
          | but_10_and_unfl_1_sva_1);
      cx_out_imag_4_0_sva_dfm <= ~(but_8_nor_19_cse | but_8_and_unfl_3_sva_1);
      cx_out_imag_6_0_sva_dfm <= ~((~((but_10_acc_14_psp_sva_1[0]) | but_10_nor_ovfl_3_sva_1))
          | but_10_and_unfl_3_sva_1);
      cx_out_imag_0_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_8_nor_12_cse, 21'b111111111111111111111,
          but_8_and_unfl_1_sva_1));
      cx_out_imag_2_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_10_nor_12_nl, 21'b111111111111111111111,
          but_10_and_unfl_1_sva_1));
      cx_out_imag_4_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_8_nor_18_cse, 21'b111111111111111111111,
          but_8_and_unfl_3_sva_1));
      cx_out_imag_6_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_10_nor_18_nl, 21'b111111111111111111111,
          but_10_and_unfl_3_sva_1));
      but_8_acc_12_psp_lpi_1_dfm_23 <= z_out[23];
      but_10_acc_12_psp_lpi_1_dfm_23 <= but_10_acc_12_psp_sva_1[23];
      but_8_acc_14_psp_lpi_1_dfm_23 <= z_out_1[23];
      but_10_acc_14_psp_lpi_1_dfm_23 <= but_10_acc_14_psp_sva_1[23];
      but_8_acc_psp_lpi_1_dfm_23 <= z_out_2[23];
      but_10_acc_psp_lpi_1_dfm_23 <= but_10_acc_psp_sva_1[23];
      but_8_acc_13_psp_lpi_1_dfm_23 <= z_out_3[23];
      but_10_acc_13_psp_lpi_1_dfm_23 <= but_10_acc_13_psp_sva_1[23];
      cx_out_real_0_0_sva_dfm <= ~(but_8_nor_10_cse | but_8_and_unfl_sva_1);
      cx_out_real_2_0_sva_dfm <= ~((~((but_10_acc_psp_sva_1[0]) | but_10_nor_ovfl_sva_1))
          | but_10_and_unfl_sva_1);
      cx_out_real_4_0_sva_dfm <= ~(but_8_nor_16_cse | but_8_and_unfl_2_sva_1);
      cx_out_real_6_0_sva_dfm <= ~((~((but_10_acc_13_psp_sva_1[0]) | but_10_nor_ovfl_2_sva_1))
          | but_10_and_unfl_2_sva_1);
      cx_out_real_0_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_8_nor_9_cse, 21'b111111111111111111111,
          but_8_and_unfl_sva_1));
      cx_out_real_2_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_10_nor_9_nl, 21'b111111111111111111111,
          but_10_and_unfl_sva_1));
      cx_out_real_4_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_8_nor_15_cse, 21'b111111111111111111111,
          but_8_and_unfl_2_sva_1));
      cx_out_real_6_21_1_sva_dfm <= ~(MUX_v_21_2_2(but_10_nor_15_nl, 21'b111111111111111111111,
          but_10_and_unfl_2_sva_1));
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_20 ) begin
      cx_in_imag_3_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_25 ) begin
      cx_in_imag_7_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_20 ) begin
      cx_in_real_3_sva <= in_real;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_25 ) begin
      cx_in_real_7_sva <= in_real;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_30 ) begin
      cx_in_imag_1_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_34 ) begin
      cx_in_imag_5_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_30 ) begin
      cx_in_real_1_sva <= in_real;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_34 ) begin
      cx_in_real_5_sva <= in_real;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_39 ) begin
      cx_in_imag_2_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_43 ) begin
      cx_in_imag_6_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_39 ) begin
      cx_in_real_2_sva <= in_real;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_43 ) begin
      cx_in_real_6_sva <= in_real;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_48 ) begin
      cx_in_imag_0_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_52 ) begin
      cx_in_imag_4_sva <= in_img;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_48 ) begin
      cx_in_real_0_sva <= in_real;
    end
  end
  always @(posedge clk) begin
    if ( ~ or_dcpl_52 ) begin
      cx_in_real_4_sva <= in_real;
    end
  end
  assign but_7_nor_15_nl = ~(MUX_v_21_2_2((but_7_acc_13_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_7_nor_ovfl_2_sva_1));
  assign but_7_but_7_nor_7_nl = ~(MUX_v_21_2_2(but_7_nor_15_nl, 21'b111111111111111111111,
      but_7_and_unfl_2_sva_1));
  assign but_7_but_7_nor_8_nl = ~((~((but_7_acc_13_psp_sva_1[0]) | but_7_nor_ovfl_2_sva_1))
      | but_7_and_unfl_2_sva_1);
  assign nl_but_11_mul_psp_sva_1  = $signed(({(but_7_acc_13_psp_sva_1[23]) , but_7_but_7_nor_7_nl
      , but_7_but_7_nor_8_nl})) * $signed(6'b101001);
  assign but_7_nor_18_nl = ~(MUX_v_21_2_2((but_7_acc_14_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_7_nor_ovfl_3_sva_1));
  assign but_7_but_7_nor_10_nl = ~(MUX_v_21_2_2(but_7_nor_18_nl, 21'b111111111111111111111,
      but_7_and_unfl_3_sva_1));
  assign but_7_but_7_nor_11_nl = ~((~((but_7_acc_14_psp_sva_1[0]) | but_7_nor_ovfl_3_sva_1))
      | but_7_and_unfl_3_sva_1);
  assign nl_but_11_mul_1_psp_sva_1  = $signed(({(but_7_acc_14_psp_sva_1[23]) , but_7_but_7_nor_10_nl
      , but_7_but_7_nor_11_nl})) * $signed(6'b101001);
  assign but_5_nor_18_nl = ~(MUX_v_21_2_2((but_5_acc_14_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_5_nor_ovfl_3_sva_1));
  assign but_5_nor_15_nl = ~(MUX_v_21_2_2((but_5_acc_13_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_5_nor_ovfl_2_sva_1));
  assign nl_but_9_mul_2_psp_sva_1  = $signed(({(but_7_acc_psp_sva_1[23]) , but_7_conc_78_21_1
      , but_7_conc_78_0})) * $signed(6'b101001);
  assign nl_but_9_mul_3_psp_sva_1  = $signed(({(but_7_acc_12_psp_sva_1[23]) , but_7_conc_76_21_1
      , but_7_conc_76_0})) * $signed(6'b010111);
  assign but_5_nor_12_nl = ~(MUX_v_21_2_2((but_5_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_5_nor_ovfl_1_sva_1));
  assign nl_but_9_mul_psp_sva_1  = $signed(({(but_7_acc_psp_sva_1[23]) , but_7_conc_78_21_1
      , but_7_conc_78_0})) * $signed(6'b010111);
  assign nl_but_9_mul_1_psp_sva_1  = $signed(({(but_7_acc_12_psp_sva_1[23]) , but_7_conc_76_21_1
      , but_7_conc_76_0})) * $signed(6'b101001);
  assign but_5_nor_9_nl = ~(MUX_v_21_2_2((but_5_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_5_nor_ovfl_sva_1));
  assign while_if_mux_2_nl = MUX_s_1_2_2(while_if_while_if_and_1_mx0w0, j_sva_3,
      or_dcpl_10);
  assign but_4_nor_18_nl = ~(MUX_v_21_2_2((but_4_acc_14_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_4_nor_ovfl_3_sva_1));
  assign but_4_nor_15_nl = ~(MUX_v_21_2_2((but_4_acc_13_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_4_nor_ovfl_2_sva_1));
  assign but_6_nor_15_nl = ~(MUX_v_21_2_2((but_6_acc_13_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_6_nor_ovfl_2_sva_1));
  assign but_6_nor_18_nl = ~(MUX_v_21_2_2((but_6_acc_14_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_6_nor_ovfl_3_sva_1));
  assign but_4_nor_12_nl = ~(MUX_v_21_2_2((but_4_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_4_nor_ovfl_1_sva_1));
  assign but_6_nor_12_nl = ~(MUX_v_21_2_2((but_6_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_6_nor_ovfl_1_sva_1));
  assign but_4_nor_9_nl = ~(MUX_v_21_2_2((but_4_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_4_nor_ovfl_sva_1));
  assign but_6_nor_9_nl = ~(MUX_v_21_2_2((but_6_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_6_nor_ovfl_sva_1));
  assign but_7_but_3_or_2_nl = MUX_v_21_2_2(but_8_nor_18_cse, 21'b111111111111111111111,
      but_8_and_unfl_3_sva_1);
  assign but_7_but_3_or_3_nl = but_8_nor_19_cse | but_8_and_unfl_3_sva_1;
  assign nl_but_7_mul_2_psp_sva_1  = conv_s2s_23_24({(~ (z_out_1[23])) , but_7_but_3_or_2_nl
      , but_7_but_3_or_3_nl}) + 24'b000000000000000000000001;
  assign but_2_nor_18_nl = ~(MUX_v_21_2_2((but_2_acc_14_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_2_nor_ovfl_3_sva_1));
  assign but_2_nor_15_nl = ~(MUX_v_21_2_2((but_2_acc_13_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_2_nor_ovfl_2_sva_1));
  assign but_7_but_3_or_nl = MUX_v_21_2_2(but_8_nor_15_cse, 21'b111111111111111111111,
      but_8_and_unfl_2_sva_1);
  assign but_7_but_3_or_1_nl = but_8_nor_16_cse | but_8_and_unfl_2_sva_1;
  assign nl_but_7_mul_1_psp_sva_1  = conv_s2s_23_24({(~ (z_out_3[23])) , but_7_but_3_or_nl
      , but_7_but_3_or_1_nl}) + 24'b000000000000000000000001;
  assign but_5_but_1_or_2_nl = MUX_v_21_2_2(but_8_nor_12_cse, 21'b111111111111111111111,
      but_8_and_unfl_1_sva_1);
  assign but_5_but_1_or_3_nl = but_8_nor_13_cse | but_8_and_unfl_1_sva_1;
  assign nl_but_5_mul_2_psp_sva_1  = conv_s2s_23_24({(~ (z_out[23])) , but_5_but_1_or_2_nl
      , but_5_but_1_or_3_nl}) + 24'b000000000000000000000001;
  assign but_nor_18_nl = ~(MUX_v_21_2_2((but_acc_14_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_nor_ovfl_3_sva_1));
  assign but_nor_15_nl = ~(MUX_v_21_2_2((but_acc_13_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_nor_ovfl_2_sva_1));
  assign but_5_but_1_or_nl = MUX_v_21_2_2(but_8_nor_9_cse, 21'b111111111111111111111,
      but_8_and_unfl_sva_1);
  assign but_5_but_1_or_1_nl = but_8_nor_10_cse | but_8_and_unfl_sva_1;
  assign nl_but_5_mul_1_psp_sva_1  = conv_s2s_23_24({(~ (z_out_2[23])) , but_5_but_1_or_nl
      , but_5_but_1_or_1_nl}) + 24'b000000000000000000000001;
  assign but_10_nor_12_nl = ~(MUX_v_21_2_2((but_10_acc_12_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_10_nor_ovfl_1_sva_1));
  assign but_10_nor_18_nl = ~(MUX_v_21_2_2((but_10_acc_14_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_10_nor_ovfl_3_sva_1));
  assign but_10_nor_9_nl = ~(MUX_v_21_2_2((but_10_acc_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_10_nor_ovfl_sva_1));
  assign but_10_nor_15_nl = ~(MUX_v_21_2_2((but_10_acc_13_psp_sva_1[21:1]), 21'b111111111111111111111,
      but_10_nor_ovfl_2_sva_1));
  assign but_8_mux_28_nl = MUX_s_1_2_2(but_4_slc_but_4_acc_12_psp_23_2_itm_1, (cx_in_real_2_sva_mx0[22]),
      xor_dcpl);
  assign but_8_mux_29_nl = MUX_v_21_2_2(fft_stage2_imag_0_21_1_sva_1, (cx_in_real_2_sva_mx0[21:1]),
      xor_dcpl);
  assign but_8_mux_30_nl = MUX_s_1_2_2(fft_stage2_imag_0_0_sva_1, (cx_in_real_2_sva_mx0[0]),
      xor_dcpl);
  assign but_8_mux_31_nl = MUX_s_1_2_2(but_6_slc_but_6_acc_12_psp_23_2_itm_1, (~
      (cx_in_real_6_sva_mx0[22])), xor_dcpl);
  assign but_8_mux_32_nl = MUX_v_21_2_2(but_6_conc_9_ncse_21_1_sva_1, (~ (cx_in_real_6_sva_mx0[21:1])),
      xor_dcpl);
  assign but_8_mux_33_nl = MUX_s_1_2_2(but_6_conc_9_ncse_0_sva_1, (~ (cx_in_real_6_sva_mx0[0])),
      xor_dcpl);
  assign nl_acc_nl = conv_s2u_24_25({but_8_mux_28_nl , but_8_mux_29_nl , but_8_mux_30_nl
      , but_8_or_cse}) + conv_s2u_24_25({but_8_mux_31_nl , but_8_mux_32_nl , but_8_mux_33_nl
      , 1'b1});
  assign acc_nl = nl_acc_nl[24:0];
  assign z_out = readslicef_25_24_1(acc_nl);
  assign but_8_mux_34_nl = MUX_s_1_2_2(but_4_slc_but_4_acc_12_psp_23_2_itm_1, (cx_in_real_3_sva_mx0[22]),
      xor_dcpl);
  assign but_8_mux_35_nl = MUX_v_21_2_2(fft_stage2_imag_0_21_1_sva_1, (cx_in_real_3_sva_mx0[21:1]),
      xor_dcpl);
  assign but_8_mux_36_nl = MUX_s_1_2_2(fft_stage2_imag_0_0_sva_1, (cx_in_real_3_sva_mx0[0]),
      xor_dcpl);
  assign but_8_mux_37_nl = MUX_s_1_2_2((~ but_6_slc_but_6_acc_12_psp_23_2_itm_1),
      (~ (cx_in_real_7_sva_mx0[22])), xor_dcpl);
  assign but_8_mux_38_nl = MUX_v_21_2_2((~ but_6_conc_9_ncse_21_1_sva_1), (~ (cx_in_real_7_sva_mx0[21:1])),
      xor_dcpl);
  assign but_8_mux_39_nl = MUX_s_1_2_2((~ but_6_conc_9_ncse_0_sva_1), (~ (cx_in_real_7_sva_mx0[0])),
      xor_dcpl);
  assign nl_acc_1_nl = conv_s2u_24_25({but_8_mux_34_nl , but_8_mux_35_nl , but_8_mux_36_nl
      , 1'b1}) + conv_s2u_24_25({but_8_mux_37_nl , but_8_mux_38_nl , but_8_mux_39_nl
      , 1'b1});
  assign acc_1_nl = nl_acc_1_nl[24:0];
  assign z_out_1 = readslicef_25_24_1(acc_1_nl);
  assign but_8_mux_40_nl = MUX_s_1_2_2(but_4_slc_but_4_acc_psp_23_2_itm_1, (cx_in_imag_2_sva_mx0[22]),
      xor_dcpl);
  assign but_8_mux_41_nl = MUX_v_21_2_2(fft_stage2_real_0_21_1_sva_1, (cx_in_imag_2_sva_mx0[21:1]),
      xor_dcpl);
  assign but_8_mux_42_nl = MUX_s_1_2_2(fft_stage2_real_0_0_sva_1, (cx_in_imag_2_sva_mx0[0]),
      xor_dcpl);
  assign but_8_mux_43_nl = MUX_s_1_2_2(but_6_slc_but_6_acc_psp_23_2_itm_1, (~ (cx_in_imag_6_sva_mx0[22])),
      xor_dcpl);
  assign but_8_mux_44_nl = MUX_v_21_2_2(but_6_conc_8_ncse_21_1_sva_1, (~ (cx_in_imag_6_sva_mx0[21:1])),
      xor_dcpl);
  assign but_8_mux_45_nl = MUX_s_1_2_2(but_6_conc_8_ncse_0_sva_1, (~ (cx_in_imag_6_sva_mx0[0])),
      xor_dcpl);
  assign nl_acc_2_nl = conv_s2u_24_25({but_8_mux_40_nl , but_8_mux_41_nl , but_8_mux_42_nl
      , but_8_or_cse}) + conv_s2u_24_25({but_8_mux_43_nl , but_8_mux_44_nl , but_8_mux_45_nl
      , 1'b1});
  assign acc_2_nl = nl_acc_2_nl[24:0];
  assign z_out_2 = readslicef_25_24_1(acc_2_nl);
  assign but_8_mux_46_nl = MUX_s_1_2_2(but_4_slc_but_4_acc_psp_23_2_itm_1, (cx_in_imag_3_sva_mx0[22]),
      xor_dcpl);
  assign but_8_mux_47_nl = MUX_v_21_2_2(fft_stage2_real_0_21_1_sva_1, (cx_in_imag_3_sva_mx0[21:1]),
      xor_dcpl);
  assign but_8_mux_48_nl = MUX_s_1_2_2(fft_stage2_real_0_0_sva_1, (cx_in_imag_3_sva_mx0[0]),
      xor_dcpl);
  assign but_8_mux_49_nl = MUX_s_1_2_2((~ but_6_slc_but_6_acc_psp_23_2_itm_1), (~
      (cx_in_imag_7_sva_mx0[22])), xor_dcpl);
  assign but_8_mux_50_nl = MUX_v_21_2_2((~ but_6_conc_8_ncse_21_1_sva_1), (~ (cx_in_imag_7_sva_mx0[21:1])),
      xor_dcpl);
  assign but_8_mux_51_nl = MUX_s_1_2_2((~ but_6_conc_8_ncse_0_sva_1), (~ (cx_in_imag_7_sva_mx0[0])),
      xor_dcpl);
  assign nl_acc_3_nl = conv_s2u_24_25({but_8_mux_46_nl , but_8_mux_47_nl , but_8_mux_48_nl
      , 1'b1}) + conv_s2u_24_25({but_8_mux_49_nl , but_8_mux_50_nl , but_8_mux_51_nl
      , 1'b1});
  assign acc_3_nl = nl_acc_3_nl[24:0];
  assign z_out_3 = readslicef_25_24_1(acc_3_nl);

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic  MUX_s_1_8_2;
    input  input_0;
    input  input_1;
    input  input_2;
    input  input_3;
    input  input_4;
    input  input_5;
    input  input_6;
    input  input_7;
    input [2:0] sel;
    reg  result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      3'b100 : begin
        result = input_4;
      end
      3'b101 : begin
        result = input_5;
      end
      3'b110 : begin
        result = input_6;
      end
      default : begin
        result = input_7;
      end
    endcase
    MUX_s_1_8_2 = result;
  end
  endfunction


  function automatic [20:0] MUX_v_21_2_2;
    input [20:0] input_0;
    input [20:0] input_1;
    input  sel;
    reg [20:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_21_2_2 = result;
  end
  endfunction


  function automatic [20:0] MUX_v_21_8_2;
    input [20:0] input_0;
    input [20:0] input_1;
    input [20:0] input_2;
    input [20:0] input_3;
    input [20:0] input_4;
    input [20:0] input_5;
    input [20:0] input_6;
    input [20:0] input_7;
    input [2:0] sel;
    reg [20:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      3'b100 : begin
        result = input_4;
      end
      3'b101 : begin
        result = input_5;
      end
      3'b110 : begin
        result = input_6;
      end
      default : begin
        result = input_7;
      end
    endcase
    MUX_v_21_8_2 = result;
  end
  endfunction


  function automatic [22:0] MUX_v_23_2_2;
    input [22:0] input_0;
    input [22:0] input_1;
    input  sel;
    reg [22:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_23_2_2 = result;
  end
  endfunction


  function automatic [27:0] MUX_v_28_2_2;
    input [27:0] input_0;
    input [27:0] input_1;
    input  sel;
    reg [27:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_28_2_2 = result;
  end
  endfunction


  function automatic [2:0] MUX_v_3_2_2;
    input [2:0] input_0;
    input [2:0] input_1;
    input  sel;
    reg [2:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_3_2_2 = result;
  end
  endfunction


  function automatic [23:0] readslicef_25_24_1;
    input [24:0] vector;
    reg [24:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_25_24_1 = tmp[23:0];
  end
  endfunction


  function automatic [23:0] conv_s2s_23_24 ;
    input [22:0]  vector ;
  begin
    conv_s2s_23_24 = {vector[22], vector};
  end
  endfunction


  function automatic [28:0] conv_s2s_28_29 ;
    input [27:0]  vector ;
  begin
    conv_s2s_28_29 = {vector[27], vector};
  end
  endfunction


  function automatic [29:0] conv_s2s_28_30 ;
    input [27:0]  vector ;
  begin
    conv_s2s_28_30 = {{2{vector[27]}}, vector};
  end
  endfunction


  function automatic [29:0] conv_s2s_29_30 ;
    input [28:0]  vector ;
  begin
    conv_s2s_29_30 = {vector[28], vector};
  end
  endfunction


  function automatic [23:0] conv_s2u_23_24 ;
    input [22:0]  vector ;
  begin
    conv_s2u_23_24 = {vector[22], vector};
  end
  endfunction


  function automatic [24:0] conv_s2u_24_25 ;
    input [23:0]  vector ;
  begin
    conv_s2u_24_25 = {vector[23], vector};
  end
  endfunction


  function automatic [24:0] conv_u2s_1_25 ;
    input [0:0]  vector ;
  begin
    conv_u2s_1_25 = {{24{1'b0}}, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    FFT
// ------------------------------------------------------------------


module FFT (
  clk, rst, data_valid_source, data_req_sink, in_real, in_img, out_real, out_img,
      data_valid_sink, data_req_source
);
  input clk;
  input rst;
  input data_valid_source;
  input data_req_sink;
  input [22:0] in_real;
  input [22:0] in_img;
  output [22:0] out_real;
  output [22:0] out_img;
  output data_valid_sink;
  output data_req_source;



  // Interconnect Declarations for Component Instantiations 
  FFT_COMPORTEMENT FFT_COMPORTEMENT_inst (
      .clk(clk),
      .rst(rst),
      .data_valid_source(data_valid_source),
      .data_req_sink(data_req_sink),
      .in_real(in_real),
      .in_img(in_img),
      .out_real(out_real),
      .out_img(out_img),
      .data_valid_sink(data_valid_sink),
      .data_req_source(data_req_source)
    );
endmodule



