# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /homes/s21comte/CHLS/TP_sysc_filter/Filtre_NexysVideo_STUDENT/src/constraints/NexysVideo_Master.xdc

# IP: /homes/s21comte/CHLS/TP_sysc_filter/Filtre_NexysVideo_STUDENT/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
